# -*- coding: utf-8 -*-
import io

PATH = "lib/legalContentDefaults.js"

with io.open(PATH, "r", encoding="utf-8") as f:
    content = f.read()


def r1(content, old, new, label):
    c = content.count(old)
    assert c == 1, "%s: expected 1 match, found %d" % (label, c)
    return content.replace(old, new)


NEW_ENTRY = r"""  'academy-faculty-portals': {
    title: 'Faculty, Staff & Academic Portals',
    bodyHtml: `
      <p><strong>Faculty, Staff &amp; Academic Portals Framework.</strong> Using the Institutional Foundation, Academic Governance, Academic Pathways, Curriculum Framework, Department Curriculum Design, Course Catalogue, Course Specifications, Assessment, Grading &amp; Progression, and Student Lifecycle &amp; Academic Administration documents as the fixed academic foundation, this framework states who teaches and administers the Academy, what each academic role can see and do, and what each role's digital portal actually contains. It does not invent titles: every role named below is one of the Academy's own already-seeded staff positions (<code>Position.nameEn</code>), not a new legal designation created for this document. It does not redesign grading, progression, or the student journey — those are Assessment, Grading &amp; Progression's and Student Lifecycle's subject matter — it states the staff-facing structure and portals around them. Five genuinely new systems were built alongside this document rather than only described: a Senior Instructor position with a real Instructor Profile (qualifications, professional development, and performance review); an expanded Programme Coordinator dashboard with applicant, student, and graduation visibility; a Department Head instructor-assignment tool; a Faculty-wide Dean standards view; and a Quality Assurance extension covering instructor evaluation, improvement-plan tracking, an evidence repository, and student course evaluations.</p>

      <h2>1. Scope &amp; Constraints</h2>
      <p>This document defines the Academy's faculty and staff role structure (§2), the Instructor Profile now recorded for every teaching position (§3), and six portals: Student (§4), Instructor (§5), Programme Coordinator (§6), Department Head (§7), Academic Dean (§8), and Quality Assurance (§9) — followed by the role/permission matrix and cross-portal workflows that tie them together (§10) and a record of what was built versus what remains an open, founder-level decision (§11). Where a portal already existed and worked, this document states it as it already behaves rather than redesigning it; where a portal was missing a piece the brief called for and the platform's own data could genuinely support it, that piece was built as part of this pass, not merely proposed. Where a piece would require inventing data that does not exist anywhere in the platform today — most importantly, a PLO/CLO achievement-percentage calculation — this document names that gap plainly instead of fabricating numbers (§11).</p>
      <p>Every role, permission, and relationship described below is the real, already-implemented <code>Position</code> / <code>PositionPermission</code> / <code>Module</code> system (<code>lib/permissions.ts</code>, <code>prisma/seed.js</code>) and the real one-to-one assignment relations already on <code>Faculty</code>, <code>Department</code>, <code>Program</code>, and <code>StudentProfile</code> — not a parallel structure invented for this document. Two new things were added to that real system, not a competing one: a <strong>Senior Instructor</strong> position (Academic Pathways and this brief both anticipate a more senior teaching rank "where appropriate," and none previously existed), and a <strong>STAFF</strong> subject type on the Academy's existing <code>QualityReview</code> model, so an instructor evaluation is recorded the same way every other quality review already is.</p>

      <h2>2. Faculty &amp; Staff Structure</h2>
      <p>Every academic role below is a real row in the <code>Position</code> table, seeded once and referenced by every staff member's <code>StaffProfile.positionId</code> — there is no free-text "job title" a staff record can hold instead of one of these. (A separate, optional <code>StaffProfile.title</code> field exists for a personal honorific such as "Dr." or "Shaykh" alongside the position — it customizes how a name is shown, it never substitutes for the governing position.) <code>Position.isAcademic</code> marks which of these are teaching/academic roles as opposed to pure administrative ones (Registrar, Finance Officer, ICT Officer, and similar), which this document does not otherwise cover.</p>
      <div class="table-wrap"><table>
      <thead><tr><th>Role (brief)</th><th>Real seeded position</th><th>Scope relation</th><th>Portal</th></tr></thead>
      <tbody>
      <tr><td>Instructor</td><td><code>Instructor</code></td><td>Assigned per course via <code>InstructorCourse</code></td><td>Instructor Portal (§5)</td></tr>
      <tr><td>Senior Instructor</td><td><code>Senior Instructor</code> — new this document</td><td>Same as Instructor, plus <code>QUALITY_ASSURANCE</code> view</td><td>Instructor Portal (§5)</td></tr>
      <tr><td>Department Head</td><td><code>Head of Department</code></td><td><code>Department.headId</code> (unique)</td><td>Department Head Portal (§7)</td></tr>
      <tr><td>Program Coordinator</td><td><code>Programme Coordinator</code></td><td><code>Program.coordinatorId</code></td><td>Programme Coordinator Portal (§6)</td></tr>
      <tr><td>Academic Advisor</td><td><code>Academic Advisor</code></td><td><code>StudentProfile.academicAdvisorId</code>, per student</td><td>Advisor Dashboard (Student Lifecycle §7)</td></tr>
      <tr><td>Academic Dean</td><td><code>Dean</code></td><td><code>Faculty.deanId</code> (unique)</td><td>Academic Dean Portal (§8)</td></tr>
      <tr><td>Assessment / Quality personnel</td><td><code>Quality Assurance Officer</code> (plus Senior Instructor's QA view)</td><td>Institution-wide, via <code>QUALITY_ASSURANCE</code> module</td><td>Quality Assurance Portal (§9)</td></tr>
      </tbody></table></div>
      <p>Two roles named in Academic Governance and already seeded sit above this table and are unchanged by this document: <code>Academy Director</code> (institution-wide academic oversight, view-only across faculty, department, program, courses, records, and quality) and <code>Academic Administrator</code> (academic-records-facing, not department- or faculty-scoped). Neither is a "portal" in the sense of §§4–9 below; both already have working admin-console access through the same <code>PositionPermission</code> system (§10).</p>
      <p>No legal or institutional title was invented for this document. Every position in the table above already existed in <code>prisma/seed.js</code> before this pass except Senior Instructor, which was added in the same list, the same way, with the same <code>code</code>/<code>nameEn</code>/<code>nameAr</code>/<code>isAcademic</code> shape as every position around it — not as a special case.</p>

      <h2>3. Instructor Profile</h2>
      <p>Before this document, a <code>StaffProfile</code> recorded only operational facts: which faculty/department, which position, an employee number, whether active. It held nothing about who the person actually is as a teacher. This section is the profile the brief asked for, and it is now real and populated per instructor rather than only specified here.</p>
      <h3>3.1 Qualifications</h3>
      <p><code>StaffQualification</code> (one-to-many per <code>StaffProfile</code>): a <code>title</code>, an optional <code>institution</code> and <code>yearObtained</code>, and a <code>type</code> — <code>GENERAL</code> or <code>ISLAMIC</code>. The two-value split exists specifically because the brief calls out "Islamic qualifications where relevant" as distinct from general academic ones (a B.A. in Arabic Literature versus an Ijazah in Hafs recitation, for example) — both are qualifications, recorded the same way, distinguished only by this one field, never by two separate tables that could drift apart.</p>
      <h3>3.2 Specialization, experience, and languages</h3>
      <p>Added directly to <code>StaffProfile</code> rather than their own tables, since each is a single value per person, not a repeating list: <code>specialization</code> (free text — e.g. "Tafsir", "Arabic Grammar"), <code>yearsExperience</code> (integer), and <code>languages</code> (a string array — every language the instructor can teach or assist in, not only their native one).</p>
      <h3>3.3 Courses authorized to teach</h3>
      <p>This is not new: <code>InstructorCourse</code> (keyed by <code>instructorId</code> — a <code>User.id</code> — and <code>courseId</code>, unique on the pair) has been the platform's real course-assignment mechanism since before this document, already used throughout the Instructor Portal (§5) to determine which courses appear for a given instructor. This document's contribution is surfacing it, for the first time, on the instructor's own profile page as "Courses Authorized to Teach" — the same underlying rows, read rather than duplicated — and giving a Department Head a real tool to create and remove those rows for instructors in their own department (§7.2), where before only direct database seeding could set them.</p>
      <h3>3.4 Professional development</h3>
      <p><code>StaffDevelopmentRecord</code> (one-to-many per <code>StaffProfile</code>): a <code>title</code>, optional <code>provider</code>, <code>completedAt</code> date, <code>hours</code>, and an optional <code>certificateUrl</code> — a workshop attended, a certification earned, a training completed. Recorded by an administrator on the staff member's admin profile page; visible to the instructor on their own read-only profile view.</p>
      <h3>3.5 Performance review</h3>
      <p><code>StaffPerformanceReview</code>: a <code>period</code> (free text — e.g. "2026 Spring Term"), an optional <code>rating</code> (<code>NEEDS_IMPROVEMENT</code> / <code>MEETS_EXPECTATIONS</code> / <code>EXCEEDS_EXPECTATIONS</code> / <code>OUTSTANDING</code>), free-text <code>strengths</code> and <code>areasForGrowth</code>, and a <code>status</code> (<code>DRAFT</code> → <code>SUBMITTED</code> → <code>ACKNOWLEDGED</code>). A reviewer must be a real staff member holding <code>FACULTY_MATTERS</code> or <code>DEPARTMENT_MATTERS</code> edit permission — in practice a Dean or Department Head — and must have their own <code>StaffProfile</code>, since the review is recorded as one staff member reviewing another, never as an admin account with no staff identity reviewing on nobody's behalf. A reviewed instructor sees only <code>SUBMITTED</code> or <code>ACKNOWLEDGED</code> reviews on their own profile — a <code>DRAFT</code> is a reviewer's working note, not yet a recorded evaluation of the instructor.</p>
      <p>All five pieces above are shown together on one admin-facing "Teaching Profile" page per staff member (<code>/admin/staff/[id]</code>) and one instructor-facing read view (<code>/instructor-dashboard/profile</code>) — the same data, an editor's view and a subject's own view of it, never two independently-maintained copies.</p>

      <h2>4. Student Portal</h2>
      <p>The Student Portal is not one new build — every item the brief lists already exists as a real page or API, most of it predating this document, several pieces added by Student Lifecycle &amp; Academic Administration. This section states the complete set together for the first time, and names the one place a student-facing feature is not yet backed by real data.</p>
      <div class="table-wrap"><table>
      <thead><tr><th>Brief item</th><th>Where it lives</th><th>Status</th></tr></thead>
      <tbody>
      <tr><td>Application</td><td><code>/admission</code> → <code>AdmissionApplication</code></td><td>Real (Student Lifecycle §3)</td></tr>
      <tr><td>Admission status</td><td><code>StudentProfile.status</code> (<code>ADMITTED</code> before Placement)</td><td>Real (Student Lifecycle §3.4)</td></tr>
      <tr><td>Placement</td><td><code>PlacementAssessment</code>, visible on the student's own profile</td><td>Real (Student Lifecycle §4)</td></tr>
      <tr><td>Registration</td><td><code>/academics/study-plan</code>, <code>/academics/remaining-courses</code> → <code>Enrollment</code></td><td>Real (Student Lifecycle §5)</td></tr>
      <tr><td>Timetable</td><td><code>/academics/overview</code>, <code>/academics/exams</code> → <code>GET /api/calendar/timetable</code></td><td><strong>Not real — see below</strong></td></tr>
      <tr><td>Courses</td><td><code>/academics/study-plan</code>, <code>/academics/remaining-courses</code> → <code>Enrollment</code></td><td>Real</td></tr>
      <tr><td>Materials</td><td>Per-course content surfaced through <code>/academics</code> and course pages</td><td>Real</td></tr>
      <tr><td>Attendance</td><td><code>/academics/attendance</code> → <code>Attendance</code></td><td>Real (Student Lifecycle §6)</td></tr>
      <tr><td>Assignments</td><td>Course-level assignment/submission views → <code>Assignment</code> / <code>Submission</code></td><td>Real, incl. per-submission <code>feedback</code></td></tr>
      <tr><td>Assessments</td><td><code>/academics/exams</code> → <code>Exam</code> / <code>Quiz</code></td><td>Real</td></tr>
      <tr><td>Grades</td><td><code>/academics/records</code> → <code>Grade</code></td><td>Real (Assessment, Grading &amp; Progression §4)</td></tr>
      <tr><td>Academic progress</td><td><code>/academics/records</code>, <code>/academics/overview</code> → <code>TermRecord</code></td><td>Real</td></tr>
      <tr><td>Transcript</td><td><code>/academics/records</code> → <code>TranscriptIssue</code> (<code>TRANSCRIPT</code> request)</td><td>Real (Student Lifecycle §8)</td></tr>
      <tr><td>Certificates</td><td><code>/academics/graduation-documents</code> → <code>GraduationDocument</code></td><td>Real</td></tr>
      <tr><td>Advising</td><td>Advisor messaging on the student's own dashboard → <code>AdvisorMessage</code></td><td>Real (Student Lifecycle §7)</td></tr>
      <tr><td>Notifications</td><td>Platform-wide → <code>Notification</code></td><td>Real, generic (not academic-event-specific)</td></tr>
      </tbody></table></div>
      <p><strong>Genuine gap found while writing this document: the student timetable is demonstration data, not real data.</strong> <code>GET /api/calendar/timetable</code> returns a fixed, hard-coded schedule (the same three class sessions and the same named instructors for every student, every request) rather than anything derived from that student's actual <code>Enrollment</code> rows or the platform's real <code>LiveClass</code> records. This was found, not assumed, by reading the route directly. It is not fixed as part of this document — building a real timetable requires a scheduled-session model tying a course, an instructor, a day/time, and a room or link together, which does not exist today (<code>LiveClass</code> records individual sessions as they are scheduled, not a recurring weekly grid) — and that is a data-model decision for engineering, not something this content document should invent silently. It is named here so the gap is known rather than mistaken for live data (§11).</p>

      <h2>5. Instructor Portal</h2>
      <p>Real and already comprehensive before this document — the Instructor Dashboard's own tabs already covered assigned courses, roster, attendance, materials, assignments, quizzes, exams, and grading — with two gaps closed and two named honestly rather than built around.</p>
      <div class="table-wrap"><table>
      <thead><tr><th>Brief item</th><th>Where it lives</th><th>Status</th></tr></thead>
      <tbody>
      <tr><td>Assigned courses</td><td><code>/instructor-dashboard/courses</code> → <code>InstructorCourse</code></td><td>Real</td></tr>
      <tr><td>Student roster</td><td><code>/instructor-dashboard/students</code> → <code>Enrollment</code></td><td>Real</td></tr>
      <tr><td>Attendance</td><td><code>/instructor-dashboard/attendance</code> → <code>Attendance</code></td><td>Real</td></tr>
      <tr><td>Materials</td><td>Course content management from the courses tab</td><td>Real</td></tr>
      <tr><td>Assignments</td><td><code>/instructor-dashboard/assignments</code> → <code>Assignment</code> / <code>Submission</code></td><td>Real, incl. scoring and <code>feedback</code></td></tr>
      <tr><td>Quizzes</td><td><code>/instructor-dashboard/quizzes</code> → <code>Quiz</code></td><td>Real</td></tr>
      <tr><td>Assessments</td><td><code>/instructor-dashboard/exams</code> → <code>Exam</code></td><td>Real</td></tr>
      <tr><td>Grading</td><td><code>/instructor-dashboard/grades</code> → <code>Grade</code></td><td>Real</td></tr>
      <tr><td>Practical rubrics</td><td>Course Specifications, per course (text)</td><td><strong>Judgment-based, not a scoring field — open (§11)</strong></td></tr>
      <tr><td>Feedback</td><td><code>Submission.feedback</code></td><td>Real</td></tr>
      <tr><td>CLO evidence</td><td>Course Specifications' CLO tables (text)</td><td><strong>Descriptive only, not a repository — open (§11)</strong></td></tr>
      <tr><td>Teaching profile (new)</td><td><code>/instructor-dashboard/profile</code></td><td>Built this document (§3)</td></tr>
      </tbody></table></div>
      <p>Two items are named honestly as gaps rather than filled with an invented system. <strong>Practical rubrics</strong> exist today exactly as Course Specifications defined them: a written four-band or four-criterion description per course, scored by an instructor's direct observation and professional judgment — real pedagogical policy, but there is no field on <code>Grade</code> to record a rubric score by criterion (the same missing <code>practical</code> field Assessment, Grading &amp; Progression already flagged as decision 54), and no in-portal form presenting the rubric's own criteria for an instructor to score against one by one. <strong>CLO evidence</strong> is, today, the "Evidence" column already printed in each course's CLO → Teaching → Assessment → Evidence table in Course Specifications (e.g. "Quiz script, rubric score") — a description of what evidence looks like for that outcome, not an actual attached artifact per student per CLO. The evidence repository built in this document (§9.3) is a QA-review-level repository, for a program, course, department, faculty, or staff review — it is a different, and separately real, thing from a per-assignment CLO evidence record, and does not double as one.</p>

      <h2>6. Program Coordinator Portal</h2>
      <p>Before this document, the Coordinator Dashboard was a single course/prerequisite editor. It is now a five-tab operational portal, each tab reading real, scoped data — every programme this coordinator is assigned to via <code>Program.coordinatorId</code>, never every programme institution-wide.</p>
      <div class="table-wrap"><table>
      <thead><tr><th>Tab</th><th>Contents</th><th>Source</th></tr></thead>
      <tbody>
      <tr><td>Dashboard</td><td>Programme summary; applicant, active-student, and graduation-candidate counts</td><td><code>GET /api/coordinator/overview</code> — new this document</td></tr>
      <tr><td>Applicants</td><td>Admission applications naming this coordinator's programmes</td><td><code>AdmissionApplication</code>, scoped by <code>programId</code></td></tr>
      <tr><td>Students</td><td>Active students in these programmes, with status</td><td><code>StudentProfile</code></td></tr>
      <tr><td>Graduation</td><td>Graduation candidates in progress</td><td><code>GraduationApplication</code></td></tr>
      <tr><td>Curriculum</td><td>Course and prerequisite management — the original, unchanged tool</td><td><code>Course</code> / prerequisite relation</td></tr>
      </tbody></table></div>
      <p>The brief's "at-risk students," "enrollment," and "assessment" sub-items are not separately re-shown here: they are Assessment, Grading &amp; Progression's academic-standing and attendance-tier signals (Student Lifecycle §7.4), already the same signals a Programme Coordinator would need, and are not duplicated into a second, competing indicator on this dashboard. "Placement" is Academic Advising's process (Student Lifecycle §4), not the Coordinator's — a coordinator sees its result (a placed programme) once it has happened, not the assessment itself. "PLOs, CLOs, course mapping, assessment coverage" under Curriculum is the one item in this portal this document does not build: no PLO/CLO database exists to map against (§11) — the Curriculum tab manages real course and prerequisite structure, which is the part of "curriculum" that is genuinely data today.</p>

      <h2>7. Department Head Portal</h2>
      <p>The HOD Dashboard already showed department-level announcements and basic counts. This document adds real instructor and curriculum visibility, plus the ability to actually assign instructors to courses — previously only possible by direct database seeding.</p>
      <h3>7.1 Department overview</h3>
      <p><code>GET /api/hod/portal</code> (extended, not replaced) now also returns: every course belonging to a programme in this department, each with its assigned instructors; every active academic staff member in the department with their specialization; and a department performance summary (student count, at-risk count by academic standing, average recorded GPA) — the same standing signal Student Lifecycle §7.4 already defines, read at department scale rather than reinvented.</p>
      <h3>7.2 Instructor assignment</h3>
      <p><code>POST</code> / <code>DELETE /api/hod/instructor-assignments</code>: a Head of Department may assign or remove an instructor for a course, restricted to courses belonging to a programme in their own department (verified server-side against <code>Department.headId</code>, not merely trusted from the request). This writes directly to the real <code>InstructorCourse</code> model (§3.3) — the same table every other part of the platform already reads — not a parallel "assignment" record that could disagree with it.</p>
      <h3>7.3 Course review</h3>
      <p>Course-level review (a Head of Department examining a specific course's quality) is not a separate mechanism: it is a <code>QualityReview</code> with <code>subjectType: COURSE</code>, scheduled by anyone holding <code>QUALITY_ASSURANCE</code> permission (§9, §10) — a Head of Department with that permission uses the same Quality Assurance workflow every other reviewer does, rather than a second review system scoped only to department heads.</p>

      <h2>8. Academic Dean Portal</h2>
      <p>The Dean Dashboard already showed department listings and announcements. This document adds faculty-wide programme, progression, graduation, and quality visibility — the view a Dean needs to see the whole faculty at once, not department by department.</p>
      <h3>8.1 Programmes &amp; standards</h3>
      <p><code>GET /api/dean/portal</code> (extended) now also returns every programme in the faculty (with department, coordinator, course and student counts), a faculty-wide progression summary (student count, at-risk count, average GPA — the same standing signal as §7.1, at faculty scale), and graduation candidates currently in progress across the faculty.</p>
      <h3>8.2 Curriculum approvals</h3>
      <p>Not a separate approval queue: programme and course structure changes are made by Programme Coordinators (§6) and Department Heads acting within their own <code>PROGRAM_MATTERS</code> / <code>DEPARTMENT_MATTERS</code> edit permission (§10); a Dean's <code>FACULTY_MATTERS</code> edit permission already lets them view and, where warranted, personally amend any programme in their faculty — this document does not add a second, formal sign-off workflow on top of the permission system that already governs who may change what.</p>
      <h3>8.3 Quality indicators</h3>
      <p>Aggregated directly from <code>QualityReview</code> across every programme, department, course, and faculty-level subject in this faculty: total reviews, compliant/minor/major outcome counts, and open improvement plans (§9.2) — the same real review data Quality Assurance itself works from (§9), read at faculty scale rather than a separately-computed "quality score."</p>

      <h2>9. Quality Assurance Portal</h2>
      <p>Already real before this document — programme, course, department, and faculty review scheduling and completion, through one <code>QualityReview</code> model and one generically-handled <code>VALID_SUBJECT_TYPES</code> pattern. This document extends that same pattern rather than building beside it, closing three of the four gaps the brief names and naming the fourth honestly.</p>
      <h3>9.1 Instructor evaluation</h3>
      <p><code>STAFF</code> is now a fifth <code>QASubjectType</code>, following the same <code>SUBJECT_FIELD</code> pattern as <code>PROGRAM</code> / <code>COURSE</code> / <code>DEPARTMENT</code> / <code>FACULTY</code> — an instructor evaluation is a <code>QualityReview</code> whose subject is a <code>StaffProfile</code>, not a separate "InstructorEvaluation" table with its own status, outcome, and reviewer logic that could drift from the rest of Quality Assurance. The Schedule a Review page's subject-type selector now offers "Staff (Instructor Evaluation)", sourced from every active academic staff member (<code>Position.isAcademic</code>), so an evaluation can actually be scheduled and run through the same queue, findings, outcome, and completion flow as every other review type.</p>
      <h3>9.2 Improvement plans</h3>
      <p><code>QualityReview.improvementStatus</code> (<code>NOT_REQUIRED</code> / <code>PENDING</code> / <code>IN_PROGRESS</code> / <code>COMPLETED</code>) tracks a completed review's recommendation through to resolution — distinct from <code>outcome</code>, which grades the review itself. A review completed with a recommendation defaults to <code>PENDING</code>, not silently to "nothing outstanding"; a reviewer can then update its status over one or more later follow-ups (<code>update_progress</code>) without re-completing the review. The Quality Assurance overview now surfaces a live count of open improvement plans (<code>PENDING</code> or <code>IN_PROGRESS</code>) institution-wide.</p>
      <h3>9.3 Evidence repository</h3>
      <p><code>QualityReview.evidenceUrls</code> (a string array) attaches supporting documents — an observation record, a syllabus excerpt, a sample of graded work, a survey export — directly to the review they evidence, addable both when a review is completed and later during improvement-plan follow-up, rather than a separate, unlinked document store a reviewer would have to cross-reference by hand. This is, deliberately, a review-level evidence repository (§5 already distinguishes it from per-assignment CLO evidence, which remains open).</p>
      <h3>9.4 Course evaluations</h3>
      <p>The first real student-submitted course evaluation system: a student rates a course they are enrolled in (<code>ratingOverall</code> required; optional <code>ratingContent</code>, <code>ratingInstructor</code>, and free-text <code>comments</code>) through <code>POST /api/student/course-evaluations</code>, one submission per student per course (upserted, so resubmitting updates rather than duplicates), anonymous by default (<code>isAnonymous</code>, true unless the student opts out). Quality Assurance sees only the aggregate: a new "Course Evaluations" tab shows per-course response counts and average ratings and, separately, the submitted comment text — never a respondent's identity, whether or not that submission was marked anonymous, since the aggregate endpoint (<code>GET /api/qa/course-evaluations</code>) never selects <code>studentId</code> at all.</p>
      <h3>9.5 PLO achievement — the one item this document does not build</h3>
      <p><strong>Genuine, open gap, not fabricated.</strong> The brief asks for "PLO achievement" alongside course evaluations, assessment quality, and instructor evaluation. Programme Learning Outcomes and Course Learning Outcomes exist today only as descriptive text inside each course's Course Specifications document (§1) — there is no <code>ProgrammeLearningOutcome</code> or <code>CourseLearningOutcome</code> table, no link from a CLO to the specific <code>Grade</code> or <code>Submission</code> rows that would evidence a student having met it, and therefore nothing a query could honestly aggregate into an "achievement percentage." Building this for real would mean modeling the entire curriculum's CLOs and PLOs as queryable rows and mapping every relevant assessment component to them — a substantial schema and data-entry undertaking in its own right, and a founder-level scope decision, not something to approximate with an invented number in this pass (§11). "Assessment quality," "instructor evaluation," "program review," and "improvement plans" — the rest of §8's list — are real and covered by §§9.1–9.3 and the pre-existing review/subject-type system; PLO achievement alone remains open.</p>

      <h2>10. Role Matrix, Permissions &amp; Workflows</h2>
      <h3>10.1 The real permission system</h3>
      <p>Every access decision described in this document runs through one mechanism, already real: <code>requireModulePermission(module, action)</code> (<code>lib/permissions.ts</code>) checks the caller's <code>StaffProfile.position.permissions</code> — a set of <code>PositionPermission</code> rows, each granting <code>canView</code> and/or <code>canEdit</code> on one of fourteen <code>Module</code> values — with <code>SUPER_ADMIN</code> bypassing the check entirely. No portal in this document has its own separate permission logic; each calls this same function against the module its data belongs to (<code>DEPARTMENT_MATTERS</code> for the HOD portal, <code>FACULTY_MATTERS</code> for the Dean portal, <code>PROGRAM_MATTERS</code> for the Coordinator portal, <code>QUALITY_ASSURANCE</code> for the QA portal).</p>
      <div class="table-wrap"><table>
      <thead><tr><th>Position</th><th>Key modules (view / edit)</th></tr></thead>
      <tbody>
      <tr><td>Dean</td><td><code>FACULTY_MATTERS</code> (edit); <code>DEPARTMENT_MATTERS</code>, <code>PROGRAM_MATTERS</code>, <code>COURSES_GRADES</code> (view)</td></tr>
      <tr><td>Head of Department</td><td><code>DEPARTMENT_MATTERS</code> (edit); <code>PROGRAM_MATTERS</code>, <code>COURSES_GRADES</code> (view)</td></tr>
      <tr><td>Programme Coordinator</td><td><code>PROGRAM_MATTERS</code> (edit); <code>COURSES_GRADES</code> (view)</td></tr>
      <tr><td>Instructor</td><td><code>COURSES_GRADES</code> (edit)</td></tr>
      <tr><td>Senior Instructor</td><td><code>COURSES_GRADES</code> (edit); <code>QUALITY_ASSURANCE</code> (view) — new this document</td></tr>
      <tr><td>Academic Advisor</td><td><code>STUDENT_MATTERS</code> (view)</td></tr>
      <tr><td>Quality Assurance Officer</td><td><code>QUALITY_ASSURANCE</code> (edit)</td></tr>
      <tr><td>Academy Director</td><td><code>FACULTY_MATTERS</code>, <code>DEPARTMENT_MATTERS</code>, <code>PROGRAM_MATTERS</code>, <code>COURSES_GRADES</code>, <code>ACADEMIC_RECORDS</code>, <code>QUALITY_ASSURANCE</code> (view)</td></tr>
      </tbody></table></div>
      <p>This table states the same <code>positionPermissions</code> seed data already governing the admin console — it is not a second policy this document proposes, only the first place it is shown as a matrix rather than as seed-file entries.</p>
      <h3>10.2 Cross-portal workflows</h3>
      <p><strong>Instructor assignment.</strong> A Head of Department assigns an instructor to a course in their own department (§7.2) → the resulting <code>InstructorCourse</code> row is what makes that course appear in the instructor's own Instructor Portal (§5) and on their public Teaching Profile (§3.3) — one write, two portals reading it, never two.</p>
      <p><strong>Performance review.</strong> A qualifying reviewer (§3.5) opens a review in <code>DRAFT</code> on the instructor's admin profile → moves it to <code>SUBMITTED</code> when ready → the instructor sees it on their own profile (§3.5) and it becomes <code>ACKNOWLEDGED</code> once they have. Nothing in an unacknowledged review blocks any other system — this is a record, not a gate.</p>
      <p><strong>Instructor evaluation → improvement plan → evidence.</strong> Quality Assurance schedules a <code>STAFF</code> review (§9.1) against an instructor → completes it with findings, an outcome, and, if warranted, a recommendation, which sets an initial <code>improvementStatus</code> of <code>PENDING</code> (§9.2) → evidence can be attached at completion or added later (§9.3) → the plan's status is updated as work proceeds, without ever re-opening or duplicating the original review.</p>
      <p><strong>Course evaluation → quality visibility.</strong> A student submits a course evaluation (§9.4) → it is immediately reflected, anonymously, in Quality Assurance's aggregate Course Evaluations view and in that programme's Dean-level quality indicators (§8.3) — no manual aggregation step exists to be skipped or delayed.</p>

      <h2>11. Decisions Requiring Approval</h2>
      <p>Continuing the numbering from Institutional Foundation through Student Lifecycle &amp; Academic Administration.</p>
      <ol start="65">
      <li><strong>Built: Senior Instructor position and the full Instructor Profile system — action taken, not open.</strong> §2, §3: qualifications (general and Islamic), specialization, experience, languages, courses authorized to teach, professional development, and performance review, all now real and recorded per instructor.</li>
      <li><strong>Built: Programme Coordinator, Department Head, and Academic Dean portal expansions — action taken, not open.</strong> §§6–8: applicant/student/graduation visibility for coordinators, instructor assignment and department performance for heads of department, and faculty-wide programme/progression/quality visibility for deans.</li>
      <li><strong>Built: Quality Assurance instructor evaluation, improvement-plan tracking, and an evidence repository — action taken, not open.</strong> §9.1–§9.3: a fifth <code>QASubjectType</code> (<code>STAFF</code>), <code>improvementStatus</code> tracked to resolution, and <code>evidenceUrls</code> attachable at completion or during follow-up.</li>
      <li><strong>Built: student course evaluations — action taken, not open.</strong> §9.4: the first real student-submitted course evaluation system, anonymous by default, aggregated for Quality Assurance without ever exposing a respondent's identity.</li>
      <li><strong>No PLO/CLO achievement system exists — open.</strong> §9.5: Programme and Course Learning Outcomes remain document text, not queryable rows linked to real assessment data; an achievement-percentage feature needs its own schema and data-entry design before it can be built honestly, and is a founder-level scope decision this document does not make by approximation.</li>
      <li><strong>No CLO evidence repository at the assignment level — open.</strong> §5: the "Evidence" column in each course's CLO table is descriptive text, not an uploadable artifact tied to a specific student's submission; the evidence repository this document does build (§9.3) is review-level, not a substitute for this.</li>
      <li><strong>No structured practical-rubric scoring — open.</strong> §5: Practical Competency Rubrics remain document text scored by instructor judgment; no <code>practical</code> field or per-criterion scoring form exists yet (see also Assessment, Grading &amp; Progression decision 54, the same underlying schema gap).</li>
      <li><strong>Found, not fixed: the student timetable is demonstration data — open.</strong> §4: <code>GET /api/calendar/timetable</code> returns a fixed, identical schedule for every student rather than deriving one from real <code>Enrollment</code> or scheduled-session records; a real weekly timetable needs a recurring-schedule data model that does not exist today, which is an engineering scope decision, not a content correction this document can make alone.</li>
      </ol>
      <p><em>Ulul Azm Academy — Faculty, Staff &amp; Academic Portals Framework. Prepared for Founder review. This framework names every academic role from the Academy's own already-seeded positions, builds a real Instructor Profile and real expansions to the Coordinator, Department Head, Dean, and Quality Assurance portals, and states plainly — rather than approximates — the four places (PLO/CLO achievement, per-assignment CLO evidence, structured rubric scoring, and the demonstration-data timetable) where a genuinely complete portal would need further, founder-level work this document does not take upon itself to invent.</em></p>

    `.trim(),
  },
"""

content = r1(
    content,
    "      <p><em>Ulul Azm Academy — Student Lifecycle &amp; Academic Administration Framework. Prepared for Founder review. This framework states the complete learner journey and, unlike a purely descriptive document, is accompanied by two real systems built alongside it — Placement and the expanded application form — plus two structural corrections to admission approval and its admin review page. It cross-references rather than restates Assessment, Grading &amp; Progression's already-complete grading, progression, and graduation logic, and names one genuine open gap: no system exists yet for the Academy's learners once they graduate.</em></p>\n\n    `.trim(),\n  },\n};",
    "      <p><em>Ulul Azm Academy — Student Lifecycle &amp; Academic Administration Framework. Prepared for Founder review. This framework states the complete learner journey and, unlike a purely descriptive document, is accompanied by two real systems built alongside it — Placement and the expanded application form — plus two structural corrections to admission approval and its admin review page. It cross-references rather than restates Assessment, Grading &amp; Progression's already-complete grading, progression, and graduation logic, and names one genuine open gap: no system exists yet for the Academy's learners once they graduate.</em></p>\n\n    `.trim(),\n  },\n" + NEW_ENTRY + "};",
    "insert academy-faculty-portals document before closing brace",
)

with io.open(PATH, "w", encoding="utf-8") as f:
    f.write(content)

print("Model 10 document content inserted into legalContentDefaults.js")
