# -*- coding: utf-8 -*-
import io

PATH = "lib/legalContentDefaults.js"

with io.open(PATH, "r", encoding="utf-8") as f:
    content = f.read()


def r1(content, old, new, label):
    c = content.count(old)
    assert c == 1, "%s: expected 1 match, found %d" % (label, c)
    return content.replace(old, new)


NEW_ENTRY = r"""  'academy-student-lifecycle': {
    title: 'Student Lifecycle & Academic Administration',
    bodyHtml: `
      <p><strong>Student Lifecycle &amp; Academic Administration Framework.</strong> Using the Institutional Foundation, Academic Governance, Academic Pathways, Curriculum Framework, Department Curriculum Design, Course Catalogue, Course Specifications, and Assessment, Grading &amp; Progression documents as the fixed academic foundation, this framework states the complete path a learner travels from first discovering the Academy through to graduation and alumni status, and names the real, already-implemented system behind each stage. It does not redesign admissions, grading, progression, repeat-course, withdrawal, or graduation policy — Assessment, Grading &amp; Progression already sets those (§4, §7, §8) — it states the stages around and between them: how an applicant becomes a record, how a record becomes a placed and registered student, how that student is advised and tracked, and what an official student record actually consists of. Two genuinely new systems were built alongside this document rather than only described: a structured Placement workflow operationalizing Academic Pathways §8's seven-input policy, and roughly twenty new application-form fields (self-rated Qur'an/Arabic levels, pathway/department/specialization preference, learning goals, support needs, a declaration) that the live admission form previously did not collect at all.</p>

      <h2>1. Scope &amp; Constraints</h2>
      <p>This document defines the Academy's student lifecycle end to end: Discovery, Application, Admission, Placement, Enrollment, Registration, Learning, Attendance, Assessment, Results, Advising, Progression, Graduation, Certificate, and Alumni (§2). It states the application form's complete field specification (§3), the Placement workflow that now exists to operationalize Academic Pathways §8 (§4), how course registration actually happens today — both a staff-triggered bulk process and an individual request process (§5), how attendance is tracked and how intervention escalates (§6), how academic advising is assigned and used (§7), what constitutes the official student record and who can request what from it (§8), and how graduation and the alumni transition work (§9) — the last of these by cross-reference to Assessment, Grading &amp; Progression's already-complete graduation logic (§7.9, §8), not by restating it. Learning, Assessment, and Results (stages within §2) are Course Specifications' and Assessment, Grading &amp; Progression's subject matter respectively and are not redefined here beyond locating them in the journey.</p>
      <p>Where this document describes a system already live in the platform — the admission-to-decision pipeline, the Placement API, the automatic and request-based registration paths, the attendance-tier logic in <code>lib/attendancePolicy.js</code>, advisor assignment, or the graduation clearance workflow — it states that system as it actually behaves, including its real field names, model names, and function names, so this document and the code can never quietly drift apart. Two structural gaps found while writing this document are corrected as part of it, not left standing: admission approval previously created a <code>User</code> account but never the corresponding <code>StudentProfile</code>, silently breaking every downstream system keyed to that record; and a fully-built admin admissions review/decision backend had no page to use it from. Both are fixed (§3.4, §10 decisions 60–61). A third finding — real, working automatic course-registration logic that already existed but had no student-facing trigger — is documented as the deliberate staff-triggered design it already is, once traced (§5.1), not treated as a gap.</p>

      <h2>2. The Student Journey</h2>
      <p>Fourteen stages, each landing on a real system rather than a description of an intended one:</p>
      <div class="table-wrap"><table>
      <thead><tr><th>#</th><th>Stage</th><th>What happens</th><th>System of record</th></tr></thead>
      <tbody>
      <tr><td>1</td><td>Discovery</td><td>A prospective learner reaches the public Academy pages — the pathway, program, and course-catalogue documents (Academy Pathways, Course Catalogue) and the public <code>/academy</code> hub.</td><td>Public academy-* pages; no account yet</td></tr>
      <tr><td>2</td><td>Application</td><td>The applicant completes the live admission form and pays the application fee.</td><td><code>app/admission/page.js</code> → <code>AdmissionApplication</code> (§3)</td></tr>
      <tr><td>3</td><td>Admission</td><td>Academic Administration reviews the paid application and decides Approve or Reject.</td><td><code>/admin/admissions/[id]</code> → <code>/api/admin/admissions/[id]/decision</code> (§3.4)</td></tr>
      <tr><td>4</td><td>Placement</td><td>On approval, a <code>StudentProfile</code> is created in <code>ADMITTED</code> status. An academic advisor records a Placement assessment against the applicant's self-reported levels; completing it moves the student to <code>ACTIVE</code> and, where a specific programme was recommended, sets it.</td><td><code>PlacementAssessment</code>; <code>/api/advisor/placement/*</code> (§4)</td></tr>
      <tr><td>5</td><td>Enrollment</td><td>The now-<code>ACTIVE</code> student holds an account, a programme (where placed), and a department — the platform's working definition of "enrolled," distinct from being registered into specific courses (stage 6).</td><td><code>StudentProfile</code> (<code>status</code>, <code>programId</code>, <code>departmentId</code>)</td></tr>
      <tr><td>6</td><td>Registration</td><td>Actual <code>Enrollment</code> rows in specific courses are created — either in bulk by Academic Records running sequencing- and prerequisite-aware automatic assignment, or individually through a student's course add/drop request.</td><td><code>Enrollment</code>; <code>lib/courseAssignment.js</code>; <code>Request</code> (type <code>COURSE_ADD_DROP</code>) (§5)</td></tr>
      <tr><td>7</td><td>Learning</td><td>Coursework proceeds under each course's own specification — teaching activities, weekly topics, assignments.</td><td>Course Specifications (per course); <code>Assignment</code> / <code>Submission</code></td></tr>
      <tr><td>8</td><td>Attendance</td><td>Class-by-class presence is tallied per course; standing deteriorates through six graduated tiers as absence rises, with a hard 25% fail-and-repeat line.</td><td><code>Attendance</code>; <code>lib/attendancePolicy.js</code> (§6)</td></tr>
      <tr><td>9</td><td>Assessment</td><td>Knowledge and Practical assessment components are recorded per course under the weighted-profile formula.</td><td><code>Grade</code>; Assessment, Grading &amp; Progression §4</td></tr>
      <tr><td>10</td><td>Results</td><td>Scores become letter grades, GPA, and per-term academic standing.</td><td><code>Grade</code> → <code>TermRecord</code>; Assessment, Grading &amp; Progression §4.1, §4.7</td></tr>
      <tr><td>11</td><td>Advising</td><td>An assigned academic advisor monitors progress, messages the student, and refers to tutoring or remediation when standing slips.</td><td><code>StudentProfile.academicAdvisorId</code>; <code>AdvisorMessage</code>; <code>TutoringRequest</code> (§7)</td></tr>
      <tr><td>12</td><td>Progression</td><td>Prerequisite chains gate individual courses; pathway-tier completion (Foundation → Diploma) is advisor-confirmed against the tier's required course list.</td><td>Assessment, Grading &amp; Progression §7.2, §7.3</td></tr>
      <tr><td>13</td><td>Graduation</td><td>Eligibility is computed automatically; the student applies; each office clears them independently; the Registrar approves; documents are issued.</td><td><code>GraduationApplication</code> / <code>GraduationClearance</code> / <code>GraduationDocument</code>; Assessment, Grading &amp; Progression §7.9, §8 (§9)</td></tr>
      <tr><td>14</td><td>Certificate</td><td>The formal credential document is generated and stored.</td><td><code>GraduationDocument</code> (<code>type</code>: <code>CERTIFICATE</code> or <code>STATEMENT_OF_COMPLETION</code>)</td></tr>
      <tr><td>15</td><td>Alumni</td><td><code>StudentStatus</code> reaches <code>GRADUATED</code> — the terminal successful state. No further stage exists today: there is no alumni directory, network, or post-graduation engagement record distinct from a graduated account. Flagged, not invented (§9, §10 decision 64).</td><td><code>StudentProfile.status = GRADUATED</code></td></tr>
      </tbody></table></div>
      <p>The fourteen named stages of the journey are kept as fourteen, with Enrollment and Registration each landing on a genuinely distinct system (§2's table rows 5–6) rather than treated as one step, since conflating them would misstate what the platform actually does: a student can be <code>ACTIVE</code> and hold a programme (enrolled) before any specific course <code>Enrollment</code> row exists for them (registered).</p>

      <h2>3. Application</h2>
      <h3>3.1 Process</h3>
      <p>An applicant completes the public admission form in three stages (personal details; academic background and self-assessment; programme preferences and declaration) before paying the application fee through Paystack or Stripe; payment success is what actually creates the <code>AdmissionApplication</code> row, through each gateway's own initialize route — this was already true before this document and remains the single source of truth for what fields exist on a submitted application, since a form field with no corresponding line in <code>applicationFieldsData</code> in both initialize routes is collected on screen but silently never saved. Every field in §3.2 below is confirmed present in both <code>app/api/admissions/paystack/initialize/route.js</code> and <code>app/api/admissions/stripe/initialize/route.js</code>, not only in the form's on-screen state.</p>
      <h3>3.2 Application form field specification</h3>
      <p>The seeded field set already covered legal name, date of birth, contact information, residence, emergency contact, previous education (highest education, institution), study session, programme, and the six document uploads. This document's contribution is the fields that did not previously exist and are now live on the form and stored on <code>AdmissionApplication</code>:</p>
      <div class="table-wrap"><table>
      <thead><tr><th>Group</th><th>Field</th><th>Stored as</th></tr></thead>
      <tbody>
      <tr><td rowspan="1">Applicant information</td><td>Preferred name</td><td><code>preferredName</code> (String?)</td></tr>
      <tr><td rowspan="4">Programme application</td><td>Pathway preference</td><td><code>pathwayPreference</code> (String? — one of the five Academy Pathways names)</td></tr>
      <tr><td>Preferred department</td><td><code>preferredDepartmentId</code> (relation to <code>Department</code>)</td></tr>
      <tr><td>Specialization</td><td><code>specialization</code> (String?)</td></tr>
      <tr><td>Study mode (full/part-time)</td><td><code>studyMode</code> (<code>StudyMode</code>: <code>FULL_TIME</code> | <code>PART_TIME</code>)</td></tr>
      <tr><td>Islamic education background</td><td>Islamic Studies background</td><td><code>islamicStudiesBackground</code> (String? — free text)</td></tr>
      <tr><td rowspan="4">Qur'an placement (self-rated)</td><td>Reading</td><td><code>quranReadingSelf</code></td></tr>
      <tr><td>Tajweed</td><td><code>quranTajweedSelf</code></td></tr>
      <tr><td>Hifz</td><td><code>quranHifzSelf</code></td></tr>
      <tr><td>Recitation</td><td><code>quranRecitationSelf</code></td></tr>
      <tr><td rowspan="6">Arabic placement (self-rated)</td><td>Reading</td><td><code>arabicReadingSelf</code></td></tr>
      <tr><td>Writing</td><td><code>arabicWritingSelf</code></td></tr>
      <tr><td>Grammar</td><td><code>arabicGrammarSelf</code></td></tr>
      <tr><td>Vocabulary</td><td><code>arabicVocabularySelf</code></td></tr>
      <tr><td>Conversation</td><td><code>arabicConversationSelf</code></td></tr>
      <tr><td>Qur'anic Arabic</td><td><code>quranicArabicSelf</code></td></tr>
      <tr><td rowspan="2">Learning goals / support</td><td>Learning goals</td><td><code>learningGoals</code> (String?)</td></tr>
      <tr><td>Support / accessibility needs</td><td><code>supportNeeds</code> (String?)</td></tr>
      <tr><td rowspan="2">Declaration</td><td>Accepted</td><td><code>declarationAccepted</code> (Boolean, required to submit)</td></tr>
      <tr><td>Accepted at</td><td><code>declarationAcceptedAt</code> (DateTime?)</td></tr>
      </tbody></table></div>
      <p>All ten self-rated fields use one shared <code>SelfRatedLevel</code> enum — <code>NONE</code> / <code>BEGINNER</code> / <code>INTERMEDIATE</code> / <code>ADVANCED</code> / <code>PROFICIENT</code> — the applicant's own account of themselves, feeding Placement (§4) as a starting point, never as the placement result itself; that distinction is stated on the admin review screen exactly so it is never mistaken for an assessed level. The declaration is a required checkbox gating submission, not a separate document upload — the applicant affirms the accuracy of the information provided and their understanding of the Academy's academic and conduct expectations before the form can be paid for and submitted.</p>
      <p>Previously existing and unchanged: legal name, date of birth, gender, nationality, country of residence, phone, ID number, residential address, applicant category, guardian details, emergency contact, programme selection, study session, highest education, institution name, and the six required document uploads (identity document, passport picture, transcripts, certificate, testimonial, recommendation letter).</p>
      <h3>3.3 Required documents</h3>
      <p>Unchanged from the existing form: identity document, passport picture, academic transcripts, certificate, testimonial, and recommendation letter — each stored as a private object and viewable by Academic Administration through a presigned-URL viewer, never exposed as a public link.</p>
      <h3>3.4 Admission decision — the gap this document closes</h3>
      <p><strong>Correction applied.</strong> Approving an application (<code>/api/admin/admissions/[id]/decision</code>, decision <code>APPROVED</code>) already created the applicant's <code>User</code> account, but never created the corresponding <code>StudentProfile</code> — meaning every downstream system this document and Assessment, Grading &amp; Progression describe (Placement, Enrollment, Attendance, Grades, Advising, Graduation) had no record to attach to for a newly-approved student. This is corrected: approval now creates a <code>StudentProfile</code> in the same transaction as the decision, with <code>status: ADMITTED</code>, a generated student number (<code>lib/studentNumber.js</code>, format <code>ULA-&lt;year&gt;-&lt;6 digits&gt;</code>, mirroring the existing <code>applicationNumber</code> generator's uniqueness-retry pattern), and faculty/department/programme copied from the approved application's programme. <code>ADMITTED</code> deliberately does not mean the same as <code>ACTIVE</code>: it is "approved, record created, not yet placed" — Placement (§4) is what moves a student from <code>ADMITTED</code> to <code>ACTIVE</code>.</p>
      <p><strong>Second gap closed.</strong> A complete admissions review/decision backend (<code>/api/admin/admissions/[id]/review</code> and <code>/decision</code>) already existed with no page to drive it from — the admissions list page's own text claimed this was "handled by Registry/Admissions staff at their own dashboard," which was not true; that dashboard has no admissions functionality at all. A full review page now exists at <code>/admin/admissions/[id]</code>, showing every field in §3.2 grouped by section, the six documents with a working viewer, payment status, and the "Move to Under Review," "Approve &amp; Create Student Record," and "Reject" actions.</p>

      <h2>4. Placement</h2>
      <p>Academic Pathways §8 already set the placement policy: seven inputs, never age, administered by Academic Advising or the relevant Department, evidence-based rather than by request. What did not exist before this document was any system to actually run that policy against a real applicant. It now does.</p>
      <h3>4.1 Placement queue</h3>
      <p><code>GET /api/advisor/placement</code> returns every student in <code>ADMITTED</code> status, plus any student whose <code>PlacementAssessment</code> has been started but not completed — deliberately not scoped to "my advisees," matching Academic Pathways §8's framing of placement as an Academic Advising / Department function rather than one pre-assigned advisor's task (a newly admitted student usually has no advisor yet; that assignment normally follows placement, once a programme is set, §7.2). Each queue entry is joined, by email, to the applicant's own §3.2 self-reported levels and pathway preference — the starting point an assessor works from, not the result.</p>
      <h3>4.2 Recording an assessment</h3>
      <p><code>POST /api/advisor/placement/[studentId]</code> records or updates one <code>PlacementAssessment</code> per student (<code>studentId</code> is unique on the model): the same ten Qur'an/Arabic dimensions as §3.2, now assessor-recorded rather than self-reported, plus a recommended pathway, an optional recommended programme, an assessor note, and a status (<code>PENDING</code> / <code>SCHEDULED</code> / <code>IN_PROGRESS</code> / <code>COMPLETED</code>). A recommended pathway is required to reach <code>COMPLETED</code>.</p>
      <h3>4.3 The Placement → Enrollment handoff</h3>
      <p>Completing a Placement assessment (status <code>COMPLETED</code>) is the one action that moves a student's <code>StudentProfile.status</code> from <code>ADMITTED</code> to <code>ACTIVE</code>, and — where a specific programme was recommended — sets <code>StudentProfile.programId</code> to it, inside the same transaction as saving the assessment. This is the concrete system behind stage 4→5 of the journey (§2): a student is not "enrolled" in the sense this document uses the word until Placement has actually run.</p>
      <h3>4.4 Advisor dashboard</h3>
      <p>The Placement queue and assessment form are available to advisory staff from a dedicated tab on the existing Advisor Dashboard, alongside the pre-existing Advisees &amp; Messages tab — the same staff surface, not a separate tool, since Academic Pathways §8 places placement with Academic Advising in the first place.</p>
      <h3>4.5 Recognition of prior learning</h3>
      <p>Unchanged from Academic Pathways §8: an applicant's own account of prior learning (§3.2's self-rated fields) is never sufficient by itself. The Placement assessment (§4.2) is the same evidence-based process every entrant goes through, whether they are placing in fresh or seeking recognition of prior study — there is no separate, lighter RPL pathway that could become an informal way around the standard.</p>

      <h2>5. Registration</h2>
      <h3>5.1 Course registration — two real paths</h3>
      <p>Two distinct, already-implemented mechanisms register a student into specific courses; this document names both rather than only the more visible one.</p>
      <p><strong>Automatic, bulk assignment (staff-triggered).</strong> <code>computeAutoAssignableCourses</code> / <code>autoAssignCoursesForProgram</code> (<code>lib/courseAssignment.js</code>) assign a student every course in their own programme where: the course has been sequenced (<code>Course.semesterLevel</code> is set), the student has not already passed it, they are not already enrolled in it, and every one of its prerequisites has been passed — only the lowest not-yet-satisfied level is assigned at a time, so no student is registered years ahead of where they actually stand. This runs per-programme from Academic Records' own dashboard (<code>/academic-records-dashboard/auto-assign</code>, backed by <code>POST /api/records/auto-assign</code>), which also shows how many of a programme's courses are sequenced and ready. It is deliberately staff-triggered rather than automatic-on-placement — Academic Records decides when a term's registration run happens, across a whole programme at once — and is idempotent, so re-running it for an already-current student creates nothing new.</p>
      <p><strong>Individual add/drop (student-requested, staff-approved).</strong> A student requests a specific course addition or removal through the existing <code>Request</code> mechanism (<code>type: COURSE_ADD_DROP</code>, with a structured <code>courseId</code> and <code>courseAction</code> of <code>ADD</code> or <code>DROP</code> — not free text). Academic Records approves or rejects it (<code>PATCH /api/records/course-requests/[id]</code>); approval actually creates or removes the real <code>Enrollment</code> row, not merely a status flag. Both paths write to the same <code>Enrollment</code> model (<code>AccessStatus</code>: <code>PENDING</code> / <code>APPROVED</code> / <code>REVOKED</code>), so a student's registered-courses view is always one consistent list regardless of which path put a course there.</p>
      <h3>5.2 Prerequisites</h3>
      <p>Governed by Assessment, Grading &amp; Progression §7.2 and enforced identically by both registration paths above through the schema's self-referencing <code>Course.prerequisites</code> relation: a prerequisite must be passed, not merely attempted, before enrollment in the course that names it.</p>
      <h3>5.3 Approval</h3>
      <p>Bulk assignment (§5.1) requires no per-course approval — Academic Records' decision to run it for a programme is the approval. Individual add/drop requests require explicit Academic Records approval (§5.1) before the Enrollment row is created or removed; a request left <code>SUBMITTED</code> or <code>UNDER_REVIEW</code> changes nothing about the student's actual registration.</p>
      <h3>5.4 Withdrawal and repeat courses</h3>
      <p>Both are Assessment, Grading &amp; Progression's subject matter and are not restated here: course-level withdrawal via the same <code>COURSE_ADD_DROP</code> (<code>DROP</code>) request before a term's drop deadline; programme-level withdrawal (<code>StudentStatus</code> → <code>WITHDRAWN</code>) versus a temporary leave of absence or deferment (<code>StudentStatus</code> → <code>DEFERRED</code>, via the existing <code>LEAVE_OF_ABSENCE</code> / <code>DEFERMENT</code> request types) — see Assessment, Grading &amp; Progression §7.8; repeat-course policy (two attempts before requiring Academic Administration approval for a third, "latest attempt replaces" under today's schema) — see §7.7.</p>

      <h2>6. Attendance &amp; Intervention</h2>
      <p>Attendance is tracked per student per course (<code>Attendance</code>: <code>totalClasses</code>, <code>attended</code>, <code>late</code>, <code>absent</code>) and already carries a real, graduated six-tier standing system (<code>lib/attendancePolicy.js</code>) that this document formalizes as institutional policy rather than redesigns:</p>
      <div class="table-wrap"><table>
      <thead><tr><th>Absence rate</th><th>Standing</th><th>Meaning</th></tr></thead>
      <tbody>
      <tr><td>0% – 4.9%</td><td>Good Standing</td><td>Excellent attendance</td></tr>
      <tr><td>5% – 9.9%</td><td>Normal</td><td>Within expectations</td></tr>
      <tr><td>10% – 14.9%</td><td>Attendance Warning</td><td>First formal warning tier</td></tr>
      <tr><td>15% – 19.9%</td><td>Nearing Danger</td><td>Approaching the fail limit</td></tr>
      <tr><td>20% – 24.9%</td><td>Critical</td><td>One or two more absences from failing</td></tr>
      <tr><td>≥ 25%</td><td>At Risk</td><td>Has reached the fail limit — fails the course and must repeat it</td></tr>
      </tbody></table></div>
      <p>A late arrival still counts as classroom attendance for standing purposes — only true absences (<code>absent / totalClasses</code>) drive the rate. A course with no sessions recorded yet is reported "Not Started" rather than defaulting into any tier. The 25% hard line is the same automatic-fail rule Assessment, Grading &amp; Progression §4.6 already defers to; this document does not restate a second attendance-fail rule, only the tier system leading up to it. Both the instructor's Attendance view and the student's own Attendance Record page already read this same shared logic, so a student's status never reads differently depending on who is looking at it.</p>
      <h3>6.1 Intervention</h3>
      <p>The graduated tiers exist specifically so intervention can begin well before the 25% fail line: a student reaching Attendance Warning or Nearing Danger is a natural trigger for their academic advisor to make contact (<code>AdvisorMessage</code>, §7) and, if warranted, refer them to tutoring support (<code>TutoringRequest</code>, §7) before the course is lost outright. Reaching Critical or At Risk in a course, combined with the per-term academic-standing thresholds (Assessment, Grading &amp; Progression §4.7), is exactly the kind of pattern the Probation remediation process (§7.6 of that document) is designed to catch — this document does not add a second, separate attendance-triggered intervention process, since the existing academic-standing and remediation machinery already covers it once attendance and grade data are both visible to the advisor in one place (§7).</p>

      <h2>7. Academic Advising</h2>
      <h3>7.1 Advisor assignment</h3>
      <p>Each <code>StudentProfile</code> carries one <code>academicAdvisorId</code> (a direct relation to <code>StaffProfile</code>), assigned and reassigned by Academic Administration through the existing <code>/admin/advising</code> page — this is a real, already-working one-to-one assignment, not a gap this document needed to fill. A student admitted but not yet placed (§4) typically has no advisor yet; assignment normally follows Placement, once a programme is known, matching Academic Pathways §8's framing of placement itself as an Academic Advising / Department function performed ahead of, or as part of, that assignment.</p>
      <h3>7.2 Study planning</h3>
      <p>An advisor's working view of a student's plan draws on the same data Registration (§5) and Progression (Assessment, Grading &amp; Progression §7) already produce: passed and outstanding required courses, unmet prerequisites, and current pathway-tier standing. No separate "study plan" document or model exists, or is proposed here — the plan is always the live, current state of these existing records, not a document that can drift out of date.</p>
      <h3>7.3 Communication</h3>
      <p><code>AdvisorMessage</code> (sender <code>STUDENT</code> or <code>ADVISOR</code>) is the existing direct channel between a student and their advisor, already read/write from both the student portal and the advisor's own dashboard.</p>
      <h3>7.4 Progression monitoring and at-risk identification</h3>
      <p>An advisee is identified as at-risk from the same two already-computed signals this document has named throughout, read together rather than separately: per-term <code>AcademicStanding</code> (Probation or worse — Assessment, Grading &amp; Progression §4.7) and per-course attendance standing (Critical or At Risk — §6 above). Neither signal alone is treated as authoritative here; this document does not define a new combined at-risk score, since doing so would itself be new grading/standing policy outside this document's scope — it states that both existing signals are visible to an advisor and should be read together, which they were not necessarily previously understood to be.</p>
      <h3>7.5 Intervention and remediation</h3>
      <p>Governed by Assessment, Grading &amp; Progression §7.4 and §7.6 (Probation, remediation plans, course-load caps, a required tutoring referral via the existing <code>TutoringRequest</code> mechanism) — not restated here. This document's contribution is naming attendance (§6.1) as an intervention trigger an advisor should act on alongside academic standing, not only after Probation is already formally recorded.</p>
      <h3>7.6 Graduation planning</h3>
      <p>An advisor's role in graduation planning is to confirm pathway-tier completion (Assessment, Grading &amp; Progression §7.3, §8.1–8.3) as a student progresses, so that Diploma-level eligibility (computed automatically, §9 below) is not a surprise at the end — this document does not add a separate advisor sign-off step to the graduation workflow itself (§9), which already runs independently of any single advisor's confirmation.</p>

      <h2>8. Student Records</h2>
      <p>No single model or page holds "the student record" as one row — it is the coherent set of everything this document and Assessment, Grading &amp; Progression have already named, and this section states what belongs to it for the first time as a defined set rather than an implicit one:</p>
      <div class="table-wrap"><table>
      <thead><tr><th>Record component</th><th>Held in</th><th>Who can request a copy / action</th></tr></thead>
      <tbody>
      <tr><td>Application &amp; admission decision</td><td><code>AdmissionApplication</code></td><td>Academic Administration (internal); not separately requestable by the student post-decision</td></tr>
      <tr><td>Placement result</td><td><code>PlacementAssessment</code></td><td>Advisory staff (record); visible to the student via their profile</td></tr>
      <tr><td>Enrollment / registration history</td><td><code>Enrollment</code></td><td>Academic Records (§5)</td></tr>
      <tr><td>Attendance</td><td><code>Attendance</code></td><td>Student (own record), instructor, advisor</td></tr>
      <tr><td>Grades</td><td><code>Grade</code></td><td>Student (own record); Academic Records for corrections</td></tr>
      <tr><td>Per-term GPA &amp; standing</td><td><code>TermRecord</code></td><td>Student (own record); Academic Administration</td></tr>
      <tr><td>Transcript</td><td><code>TranscriptIssue</code> (generated PDF, cumulative GPA snapshot)</td><td>Student, via a <code>TRANSCRIPT</code> request</td></tr>
      <tr><td>Fees</td><td><code>StudentFee</code></td><td>Student (own record); Finance</td></tr>
      <tr><td>Requests &amp; their history</td><td><code>Request</code> / <code>RequestActivity</code></td><td>Student (own submissions); the assigned unit/staff</td></tr>
      <tr><td>Graduation &amp; clearance</td><td><code>GraduationApplication</code> / <code>GraduationClearance</code></td><td>Student (own status); each clearing office; the Registrar</td></tr>
      <tr><td>Issued credentials</td><td><code>GraduationDocument</code></td><td>Student, on request or automatically once issued</td></tr>
      </tbody></table></div>
      <p>Every one of these already has a real page or API surfacing it to the student, an advisor, or the relevant office (Academic Records' own <code>/academics/records</code> page already brings several of them together for the student) — this table is the first place they are named together as one coherent "student record" rather than as separately-built features. Requests for a copy or action on any component that is not simply self-viewable in a portal go through the existing <code>Request</code> types (<code>TRANSCRIPT</code>, <code>LETTER_CONFIRMATION</code>, <code>GRADE_APPEAL</code>, <code>COMPLAINT</code>, <code>GRADUATE_SUPPORT</code>, <code>OTHER</code>) — this document does not add a new request type for anything already covered by an existing one.</p>

      <h2>9. Graduation, Certification &amp; Alumni Transition</h2>
      <p>Graduation eligibility, application, clearance, and document issuance are fully defined and fully implemented by Assessment, Grading &amp; Progression §7.9 and §8 (<code>computeGraduationEligibility()</code>, <code>GraduationApplication</code>, <code>GraduationClearance</code> per <code>Unit</code>, <code>GraduationDocument</code>) — this document does not redesign or restate that logic, only locates it as stages 13–14 of the journey (§2) and states what comes after it, which that document does not address.</p>
      <p><strong>Alumni — a genuine, open gap.</strong> Once a <code>GraduationApplication</code> reaches <code>COMPLETED</code> and the student's account status moves to <code>GRADUATED</code>, no further system exists: there is no alumni directory, no distinct alumni record, portal, or engagement tracking separate from a graduated account sitting in its final state. Alumni is named as the journey's final stage (§2) precisely so this is stated plainly rather than filled with an invented system — an alumni programme (a directory, continuing-education pathways for a Specialized Certificate per Academy Pathways §7, or any post-graduation engagement) is a founder-level decision this document flags rather than makes (§10 below, decision 64).</p>

      <h2>10. Decisions Requiring Approval</h2>
      <p>Continuing the numbering from Institutional Foundation through Assessment, Grading &amp; Progression.</p>
      <ol start="60">
      <li><strong>Correction applied: admission approval now creates a <code>StudentProfile</code> — action taken, not open.</strong> §3.4 explains the gap this closes: without it, every system this document and Assessment, Grading &amp; Progression describe had no record to attach a newly-approved student to.</li>
      <li><strong>Correction applied: a full admin admissions review page now exists — action taken, not open.</strong> §3.4: the review/decision backend already existed; the admissions list page's claim that this was "handled at Registry/Admissions' own dashboard" was inaccurate and has been corrected along with building the page.</li>
      <li><strong>Built: the Placement workflow (<code>PlacementAssessment</code>, queue API, advisor dashboard tab) — action taken, not open.</strong> §4: this is the first real system operationalizing Academic Pathways §8's seven-input placement policy; no code previously existed for it.</li>
      <li><strong>Built: ~20 new application-form fields — action taken, not open.</strong> §3.2: pathway/department/specialization/study-mode preference, ten self-rated Qur'an/Arabic levels, Islamic Studies background, learning goals, support needs, and a required declaration, all now live on the form and stored on <code>AdmissionApplication</code>.</li>
      <li><strong>No alumni system exists beyond the <code>GRADUATED</code> status — open.</strong> §9: whether to build a directory, continuing-education pathway, or engagement tracking is a founder-level decision this document does not make.</li>
      </ol>
      <p><em>Ulul Azm Academy — Student Lifecycle &amp; Academic Administration Framework. Prepared for Founder review. This framework states the complete learner journey and, unlike a purely descriptive document, is accompanied by two real systems built alongside it — Placement and the expanded application form — plus two structural corrections to admission approval and its admin review page. It cross-references rather than restates Assessment, Grading &amp; Progression's already-complete grading, progression, and graduation logic, and names one genuine open gap: no system exists yet for the Academy's learners once they graduate.</em></p>

    `.trim(),
  },
"""

content = r1(
    content,
    "      <p><em>Ulul Azm Academy — Assessment, Grading &amp; Progression Framework. Prepared for Founder review. This framework codifies and extends the Academy's existing, already-implemented grading and eligibility logic (grading scale, GPA formula, attendance-fail rule, graduation-eligibility check) rather than replacing it, corrects one real conflict found between that live system and the Course Specifications' published course specifications (decision 52, now applied), and names eight further gaps between what this framework specifies and what the current schema can store or enforce — none of which block using this document as the Academy's working assessment policy; they block only the specific automated checks each one touches.</em></p>\n\n    `.trim(),\n  },\n};",
    "      <p><em>Ulul Azm Academy — Assessment, Grading &amp; Progression Framework. Prepared for Founder review. This framework codifies and extends the Academy's existing, already-implemented grading and eligibility logic (grading scale, GPA formula, attendance-fail rule, graduation-eligibility check) rather than replacing it, corrects one real conflict found between that live system and the Course Specifications' published course specifications (decision 52, now applied), and names eight further gaps between what this framework specifies and what the current schema can store or enforce — none of which block using this document as the Academy's working assessment policy; they block only the specific automated checks each one touches.</em></p>\n\n    `.trim(),\n  },\n" + NEW_ENTRY + "};",
    "insert academy-student-lifecycle document before closing brace",
)

with io.open(PATH, "w", encoding="utf-8") as f:
    f.write(content)

print("Model 9 document content inserted into legalContentDefaults.js")
