# -*- coding: utf-8 -*-
# Exact OLD -> NEW pairs for the 8 opening framing paragraphs and 8 closing
# signature paragraphs in lib/legalContentDefaults.js. Each OLD string must
# match exactly once in the file.

OPENING_PAIRS = [
(
"""      <p><strong>Model 1 — Institutional Foundation.</strong> This is Ulul Azm Academy's institutional identity, educational philosophy, the learners it serves, and the principles that will govern every curriculum, program and course decision that follows. No courses, programs or curricula are designed here — this establishes the ground they will stand on. It is a living foundation document, expected to be revisited as the Academy matures.</p>""",
"""      <p><strong>Institutional Foundation.</strong> This document sets out Ulul Azm Academy's institutional identity, educational philosophy, the learners it serves, and the principles that govern every curriculum, program and course decision that follows. No courses, programs or curricula are designed here — this establishes the ground they stand on. It is a living foundation document, revisited as the Academy matures.</p>""",
),
(
"""      <p><strong>Model 2 — Academic Governance &amp; Organizational Structure.</strong> Model 1 established the Academy's identity and educational philosophy. This model designs the professional structure that carries that philosophy out: who holds academic authority, how departments and cross-cutting units are organized, who is responsible for what, and how a curriculum decision actually moves through the system. No detailed courses, programs, or syllabi are designed here.</p>""",
"""      <p><strong>Academic Governance &amp; Organizational Structure.</strong> The Institutional Foundation document establishes the Academy's identity and educational philosophy. This document sets out the professional structure that carries that philosophy out: who holds academic authority, how departments and cross-cutting units are organized, who is responsible for what, and how a curriculum decision actually moves through the system. No detailed courses, programs, or syllabi are designed here.</p>""",
),
(
"""      <p><strong>Model 3 — Academic Pathways &amp; Qualification Framework.</strong> Models 1 and 2 established the Academy's philosophy and governance. This model defines the pathways a learner actually moves through, and the qualification structure behind them — not yet the courses that fill them.</p>""",
"""      <p><strong>Academic Pathways &amp; Qualification Framework.</strong> The Institutional Foundation and Academic Governance documents establish the Academy's philosophy and governance. This document defines the pathways a learner actually moves through, and the qualification structure behind them — not yet the courses that fill them.</p>""",
),
(
"""      <p><strong>Model 4 — Program Architecture &amp; Curriculum Framework.</strong> Models 1–3 are fixed foundations here, not renegotiated. This model turns Model 3's five pathways into a real curriculum shape — what each program actually contains, in what order, with what prerequisites — using temporary course-code placeholders. No weekly syllabi, and no final course catalogue, yet.</p>""",
"""      <p><strong>Program Architecture &amp; Curriculum Framework.</strong> The Institutional Foundation, Academic Governance, and Academic Pathways documents are fixed foundations here, not renegotiated. This document turns the Academic Pathways framework's five pathways into a real curriculum shape — what each program actually contains, in what order, with what prerequisites — using temporary course-code placeholders. No weekly syllabi, and no final course catalogue, yet.</p>""",
),
(
"""      <p><strong>Model 5 — Department &amp; Program Curriculum Design.</strong> Models 1–4 are fixed foundations here, not renegotiated. This model answers a question Model 4 deliberately left open: not every program should have the same courses, and not every course belongs to the department someone might guess first. It gives each of the Academy's five departments a defined topic list, resolves every place two departments' topics appeared to overlap, and corrects two course attributions Models 3 and 4 got wrong before this model existed to catch them. No weekly syllabi, and no final course catalogue, yet.</p>""",
"""      <p><strong>Department &amp; Program Curriculum Design.</strong> The Institutional Foundation, Academic Governance, Academic Pathways, and Curriculum Framework documents are fixed foundations here, not renegotiated. This document answers a question the Curriculum Framework deliberately left open: not every program should have the same courses, and not every course belongs to the department someone might guess first. It gives each of the Academy's five departments a defined topic list, resolves every place two departments' topics appeared to overlap, and corrects two course attributions the Academic Pathways and Curriculum Framework documents got wrong before this document existed to catch them. No weekly syllabi, and no final course catalogue, yet.</p>""",
),
(
"""      <p><strong>Model 6 — Course Catalogue &amp; Coding System.</strong> Models 1–5 are fixed foundations here, not renegotiated. This model turns every course named across Models 4 and 5 into one master catalogue: a permanent coding system (closing Model 4 decision 23), a numbering framework that encodes academic level without guesswork, full course-level detail for all 42 courses identified so far, and the quality-control and gap audits a real catalogue needs before any of it becomes actual <code>Course</code> records. Codes in Models 4 and 5 have been updated to match this model throughout. No weekly syllabi yet.</p>""",
"""      <p><strong>Course Catalogue &amp; Coding System.</strong> The Institutional Foundation, Academic Governance, Academic Pathways, Curriculum Framework, and Department Curriculum Design documents are fixed foundations here, not renegotiated. This catalogue turns every course named across the Curriculum Framework and Department Curriculum Design documents into one master catalogue: a permanent coding system (closing Curriculum Framework decision 23), a numbering framework that encodes academic level without guesswork, full course-level detail for all 42 courses identified so far, and the quality-control and gap audits a real catalogue needs before any of it becomes actual <code>Course</code> records. Codes in the Curriculum Framework and Department Curriculum Design documents have been updated to match this catalogue throughout. No weekly syllabi yet.</p>""",
),
(
"""      <p><strong>Model 7 — Course Specifications &amp; Syllabi.</strong> Models 1–6 are the fixed academic foundation here — this model does not redesign departments, programs, prerequisites, or the course catalogue. It takes each catalogued course and adds the syllabus-level detail Model 6 deliberately didn't attempt: weekly sequencing, measurable learning outcomes, teaching methodology, assessment design, and a CLO → Teaching → Assessment → Evidence map. Where Model 6 already defined a field correctly (code, title, department, program, pathway, level, units, hours, prerequisites, type), this model carries it forward rather than re-deriving it. Because 42 courses is too much for one response, this model is built in batches — see §4 for how batches are sequenced and reported.</p>""",
"""      <p><strong>Course Specifications &amp; Syllabi.</strong> The Institutional Foundation, Academic Governance, Academic Pathways, Curriculum Framework, Department Curriculum Design, and Course Catalogue documents are the fixed academic foundation here — this document does not redesign departments, programs, prerequisites, or the course catalogue. It takes each catalogued course and adds the syllabus-level detail the Course Catalogue deliberately didn't attempt: weekly sequencing, measurable learning outcomes, teaching methodology, assessment design, and a CLO → Teaching → Assessment → Evidence map. Where the Course Catalogue already defined a field correctly (code, title, department, program, pathway, level, units, hours, prerequisites, type), this document carries it forward rather than re-deriving it. Because 42 courses is too much to specify at once, this document was compiled in batches — see §4 for how batches are sequenced and reported.</p>""",
),
(
"""      <p><strong>Model 8 — Assessment, Grading &amp; Progression Framework.</strong> Using Models 1–7 as the fixed academic foundation, this model defines how the Academy measures, grades, and progresses learners: the two assessment families, CLO/PLO alignment, the grading scale, practical rubrics, progression rules, and graduation requirements per pathway tier. It does not redesign departments, programs, prerequisites, the course catalogue, or any course's own specification (Models 4–7); it formalizes how those are measured. Where the platform already has real, live grading and eligibility logic, this model codifies that logic rather than inventing a second one — and corrects the one real conflict found between that live logic and Model 7's published text (§4.3, §9 decision 52).</p>""",
"""      <p><strong>Assessment, Grading &amp; Progression Framework.</strong> Using the Institutional Foundation, Academic Governance, Academic Pathways, Curriculum Framework, Department Curriculum Design, Course Catalogue, and Course Specifications documents as the fixed academic foundation, this framework defines how the Academy measures, grades, and progresses learners: the two assessment families, CLO/PLO alignment, the grading scale, practical rubrics, progression rules, and graduation requirements per pathway tier. It does not redesign departments, programs, prerequisites, the course catalogue, or any course's own specification (the Curriculum Framework through Course Specifications documents); it formalizes how those are measured. Where the platform already has real, live grading and eligibility logic, this framework codifies that logic rather than inventing a second one — and corrects the one real conflict found between that live logic and the Course Specifications' published text (§4.3, §9 decision 52).</p>""",
),
]

CLOSING_PAIRS = [
(
"""      <p><em>Ulul Azm Academy — Institutional Foundation, Model 1. Prepared for Founder review. Items marked "open" are not yet in effect as institutional policy; the manhaj confirmed in §2 and §12 is in effect.</em></p>""",
"""      <p><em>Ulul Azm Academy — Institutional Foundation. Prepared for Founder review. Items marked "open" are not yet in effect as institutional policy; the manhaj confirmed in §2 and §12 is in effect.</em></p>""",
),
(
"""      <p><em>Ulul Azm Academy — Academic Governance &amp; Organizational Structure, Model 2. Prepared for Founder review. The Academy Director role and its permissions are already live in the system; the department, committee and cross-cutting-unit structures above are confirmed design, awaiting the schema and data decisions in this section before they become real, tracked functionality.</em></p>""",
"""      <p><em>Ulul Azm Academy — Academic Governance &amp; Organizational Structure. Prepared for Founder review. The Academy Director role and its permissions are already live in the system; the department, committee and cross-cutting-unit structures above are confirmed design, awaiting the schema and data decisions in this section before they become real, tracked functionality.</em></p>""",
),
(
"""      <p><em>Ulul Azm Academy — Academic Pathways &amp; Qualification Framework, Model 3. Prepared for Founder review. The Diploma in Islamic Studies is being created as a real Program record alongside this document; Foundation, Intermediate and Advanced remain framework-only until decision 20 above is resolved.</em></p>""",
"""      <p><em>Ulul Azm Academy — Academic Pathways &amp; Qualification Framework. Prepared for Founder review. The Diploma in Islamic Studies is being created as a real Program record alongside this document; Foundation, Intermediate and Advanced remain framework-only until decision 20 above is resolved.</em></p>""",
),
(
"""      <p><em>Ulul Azm Academy — Program Architecture &amp; Curriculum Framework, Model 4. Prepared for Founder review. This model's courses are illustrative placeholders that fix the Academy's curriculum shape — they are not yet real Course records, and none should be created until decision 22 above is resolved (decision 23 has since been resolved by Model 6).</em></p>""",
"""      <p><em>Ulul Azm Academy — Program Architecture &amp; Curriculum Framework. Prepared for Founder review. This document's courses are illustrative placeholders that fix the Academy's curriculum shape — they are not yet real Course records, and none should be created until decision 22 above is resolved (decision 23 has since been resolved by the Course Catalogue).</em></p>""",
),
(
"""      <p><em>Ulul Azm Academy — Department &amp; Program Curriculum Design, Model 5. Prepared for Founder review. This model's courses are illustrative placeholders, not yet real Course records; none should be created until decision 22, and 26–29 (Models 4–5), are resolved (decision 23 has since been resolved by Model 6).</em></p>""",
"""      <p><em>Ulul Azm Academy — Department &amp; Program Curriculum Design. Prepared for Founder review. This document's courses are illustrative placeholders, not yet real Course records; none should be created until decision 22, and 26–29 (Curriculum Framework and Department Curriculum Design), are resolved (decision 23 has since been resolved by the Course Catalogue).</em></p>""",
),
(
"""      <p><em>Ulul Azm Academy — Course Catalogue &amp; Coding System, Model 6. Prepared for Founder review. This catalogue's 42 courses (plus the SPEC-3xx placeholder) are illustrative — not yet real Course records — and none should be created until decision 22 (Model 4) and decisions 30–33 above are resolved.</em></p>""",
"""      <p><em>Ulul Azm Academy — Course Catalogue &amp; Coding System. Prepared for Founder review. This catalogue's 42 courses (plus the SPEC-3xx placeholder) are illustrative — not yet real Course records — and none should be created until decision 22 (Curriculum Framework) and decisions 30–33 above are resolved.</em></p>""",
),
(
"""      <p><em>Ulul Azm Academy — Course Specifications &amp; Syllabi, Model 7 — COMPLETE, all 8 of 8 batches (Foundation Studies; Intermediate Islamic Studies; Advanced Islamic Studies; Advanced Qur'anic Studies/Arabic/Civilization &amp; Society/Research; Diploma — Islamic Studies &amp; Qur'anic Studies; Diploma — Arabic &amp; Research; Diploma — Islamic Education &amp; Tarbiyah teaching track; Diploma — Islamic Civilization &amp; Society community track plus SPEC-3xx). Prepared for Founder review. All 42 courses in the Model 6 catalogue now have a full specification and syllabus, plus a framework note for SPEC-3xx. These specifications are illustrative and pending decisions 34–51 above (decision 40 now covers the whole Islamic Civilization &amp; Society department), plus every open decision inherited from Models 1–6 that a given course depends on — most centrally Model 1 §12 decision 1 (madhab adoption), the riwayah/qira'ah choice (decision 37), and IE-402's fully provisional placement (decision 32). None of these open decisions block using this document as the Academy's working course-specification reference; they block only the specific fields each one touches. Model 7 is complete — ready for Model 8.</em></p>""",
"""      <p><em>Ulul Azm Academy — Course Specifications &amp; Syllabi — COMPLETE, all 8 of 8 batches (Foundation Studies; Intermediate Islamic Studies; Advanced Islamic Studies; Advanced Qur'anic Studies/Arabic/Civilization &amp; Society/Research; Diploma — Islamic Studies &amp; Qur'anic Studies; Diploma — Arabic &amp; Research; Diploma — Islamic Education &amp; Tarbiyah teaching track; Diploma — Islamic Civilization &amp; Society community track plus SPEC-3xx). Prepared for Founder review. All 42 courses in the Course Catalogue now have a full specification and syllabus, plus a framework note for SPEC-3xx. These specifications are illustrative and pending decisions 34–51 above (decision 40 now covers the whole Islamic Civilization &amp; Society department), plus every open decision inherited from earlier documents that a given course depends on — most centrally Institutional Foundation §12 decision 1 (madhab adoption), the riwayah/qira'ah choice (decision 37), and IE-402's fully provisional placement (decision 32). None of these open decisions block using this document as the Academy's working course-specification reference; they block only the specific fields each one touches.</em></p>""",
),
(
"""      <p><em>Ulul Azm Academy — Assessment, Grading &amp; Progression Framework, Model 8. Prepared for Founder review. This framework codifies and extends the Academy's existing, already-implemented grading and eligibility logic (grading scale, GPA formula, attendance-fail rule, graduation-eligibility check) rather than replacing it, corrects one real conflict found between that live system and Model 7's published course specifications (decision 52, now applied), and names eight further gaps between what this framework specifies and what the current schema can store or enforce — none of which block using this document as the Academy's working assessment policy; they block only the specific automated checks each one touches. Say when you're ready for Model 9.</em></p>""",
"""      <p><em>Ulul Azm Academy — Assessment, Grading &amp; Progression Framework. Prepared for Founder review. This framework codifies and extends the Academy's existing, already-implemented grading and eligibility logic (grading scale, GPA formula, attendance-fail rule, graduation-eligibility check) rather than replacing it, corrects one real conflict found between that live system and the Course Specifications' published course specifications (decision 52, now applied), and names eight further gaps between what this framework specifies and what the current schema can store or enforce — none of which block using this document as the Academy's working assessment policy; they block only the specific automated checks each one touches.</em></p>""",
),
]
