# -*- coding: utf-8 -*-
import io

def load(path):
    with io.open(path, "r", encoding="utf-8") as f:
        return f.read()

def save(path, content):
    with io.open(path, "w", encoding="utf-8") as f:
        f.write(content)

def r1(content, old, new, label):
    c = content.count(old)
    assert c == 1, "%s: expected 1 match, found %d (context: %r)" % (label, c, old[:160])
    return content.replace(old, new)

path = "app/admin/admissions/[id]/page.jsx"
c = load(path)

# 1) New state for the letter + history workflow.
c = r1(
    c,
    "  const [noteVisibility, setNoteVisibility] = useState('INTERNAL');\n"
    "  const [notePending, setNotePending] = useState(false);\n"
    "\n"
    "  const load = () => {",
    "  const [noteVisibility, setNoteVisibility] = useState('INTERNAL');\n"
    "  const [notePending, setNotePending] = useState(false);\n"
    "\n"
    "  const [letter, setLetter] = useState(null);\n"
    "  const [letterLoading, setLetterLoading] = useState(false);\n"
    "  const [letterPending, setLetterPending] = useState(false);\n"
    "  const [letterForm, setLetterForm] = useState({\n"
    "    programmeText: '',\n"
    "    departmentText: '',\n"
    "    qualificationText: '',\n"
    "    intakeSession: '',\n"
    "    admissionDate: '',\n"
    "    conditions: '',\n"
    "    signatoryName: '',\n"
    "    signatoryTitle: '',\n"
    "  });\n"
    "  const [history, setHistory] = useState([]);\n"
    "  const [historyLoading, setHistoryLoading] = useState(false);\n"
    "\n"
    "  const load = () => {",
    "letter/history state",
)

# 2) loadLetter() / loadHistory(), right after loadNotes().
c = r1(
    c,
    "  const loadNotes = () => {\n"
    "    setNotesLoading(true);\n"
    "    fetch(`/api/admin/admissions/${id}/notes`, { credentials: 'include' })\n"
    "      .then(async (res) => {\n"
    "        const result = await res.json();\n"
    "        if (res.ok && result.success) setNotes(result.data);\n"
    "      })\n"
    "      .finally(() => setNotesLoading(false));\n"
    "  };\n"
    "\n"
    "  useEffect(() => {\n"
    "    load();\n"
    "    loadNotes();\n"
    "    // eslint-disable-next-line react-hooks/exhaustive-deps\n"
    "  }, [id]);",
    "  const loadNotes = () => {\n"
    "    setNotesLoading(true);\n"
    "    fetch(`/api/admin/admissions/${id}/notes`, { credentials: 'include' })\n"
    "      .then(async (res) => {\n"
    "        const result = await res.json();\n"
    "        if (res.ok && result.success) setNotes(result.data);\n"
    "      })\n"
    "      .finally(() => setNotesLoading(false));\n"
    "  };\n"
    "\n"
    "  const loadLetter = () => {\n"
    "    setLetterLoading(true);\n"
    "    fetch(`/api/admin/admissions/${id}/letter`, { credentials: 'include' })\n"
    "      .then(async (res) => {\n"
    "        const result = await res.json();\n"
    "        if (res.ok && result.success) {\n"
    "          setLetter(result.data);\n"
    "          const d = result.data;\n"
    "          const defaults = result.defaults || {};\n"
    "          setLetterForm({\n"
    "            programmeText: d?.programmeText ?? defaults.programmeText ?? '',\n"
    "            departmentText: d?.departmentText ?? defaults.departmentText ?? '',\n"
    "            qualificationText: d?.qualificationText ?? defaults.qualificationText ?? '',\n"
    "            intakeSession: d?.intakeSession ?? defaults.intakeSession ?? '',\n"
    "            admissionDate: d?.admissionDate ? String(d.admissionDate).slice(0, 10) : '',\n"
    "            conditions: d?.conditions ?? '',\n"
    "            signatoryName: d?.signatoryName ?? '',\n"
    "            signatoryTitle: d?.signatoryTitle ?? '',\n"
    "          });\n"
    "        }\n"
    "      })\n"
    "      .finally(() => setLetterLoading(false));\n"
    "  };\n"
    "\n"
    "  const loadHistory = () => {\n"
    "    setHistoryLoading(true);\n"
    "    fetch(`/api/admin/admissions/${id}/audit`, { credentials: 'include' })\n"
    "      .then(async (res) => {\n"
    "        const result = await res.json();\n"
    "        if (res.ok && result.success) setHistory(result.data);\n"
    "      })\n"
    "      .finally(() => setHistoryLoading(false));\n"
    "  };\n"
    "\n"
    "  useEffect(() => {\n"
    "    load();\n"
    "    loadNotes();\n"
    "    loadLetter();\n"
    "    loadHistory();\n"
    "    // eslint-disable-next-line react-hooks/exhaustive-deps\n"
    "  }, [id]);",
    "loadLetter/loadHistory + useEffect wiring",
)

# 3) Handlers, right after viewDocument().
c = r1(
    c,
    "  const viewDocument = async (field) => {\n"
    "    try {\n"
    "      const res = await fetch(`/api/admin/admissions/${id}/document?field=${field}`, { credentials: 'include' });\n"
    "      const result = await res.json();\n"
    "      if (!res.ok || !result.success) throw new Error(result.error || 'Unable to open document.');\n"
    "      window.open(result.data.url, '_blank', 'noopener,noreferrer');\n"
    "    } catch (err) {\n"
    "      setActionMessage(err.message);\n"
    "    }\n"
    "  };\n"
    "\n"
    "  if (loading) return <main style={page}><div style={container}>Loading…</div></main>;",
    "  const viewDocument = async (field) => {\n"
    "    try {\n"
    "      const res = await fetch(`/api/admin/admissions/${id}/document?field=${field}`, { credentials: 'include' });\n"
    "      const result = await res.json();\n"
    "      if (!res.ok || !result.success) throw new Error(result.error || 'Unable to open document.');\n"
    "      window.open(result.data.url, '_blank', 'noopener,noreferrer');\n"
    "    } catch (err) {\n"
    "      setActionMessage(err.message);\n"
    "    }\n"
    "  };\n"
    "\n"
    "  const saveLetterDraft = async (reopen) => {\n"
    "    setLetterPending(true);\n"
    "    setActionMessage('');\n"
    "    try {\n"
    "      const res = await fetch(`/api/admin/admissions/${id}/letter`, {\n"
    "        method: 'POST',\n"
    "        credentials: 'include',\n"
    "        headers: { 'Content-Type': 'application/json' },\n"
    "        body: JSON.stringify({ ...letterForm, reopen: !!reopen }),\n"
    "      });\n"
    "      const result = await res.json();\n"
    "      if (!res.ok || !result.success) throw new Error(result.error || 'Unable to save the letter.');\n"
    "      setActionMessage(reopen ? 'Letter reopened for correction.' : 'Letter draft saved.');\n"
    "      loadLetter();\n"
    "      loadHistory();\n"
    "    } catch (err) {\n"
    "      setActionMessage(err.message);\n"
    "    } finally {\n"
    "      setLetterPending(false);\n"
    "    }\n"
    "  };\n"
    "\n"
    "  const finalizeLetter = async () => {\n"
    "    setLetterPending(true);\n"
    "    setActionMessage('');\n"
    "    try {\n"
    "      const res = await fetch(`/api/admin/admissions/${id}/letter/finalize`, {\n"
    "        method: 'POST',\n"
    "        credentials: 'include',\n"
    "      });\n"
    "      const result = await res.json();\n"
    "      if (!res.ok || !result.success) throw new Error(result.error || 'Unable to finalize the letter.');\n"
    "      const emailNote =\n"
    "        typeof result.emailSent === 'boolean'\n"
    "          ? result.emailSent\n"
    "            ? ' The applicant has been emailed.'\n"
    "            : ' (The applicant was not emailed -- admissions email is not configured yet.)'\n"
    "          : '';\n"
    "      setActionMessage((result.message || 'Letter finalized.') + emailNote);\n"
    "      loadLetter();\n"
    "      loadHistory();\n"
    "    } catch (err) {\n"
    "      setActionMessage(err.message);\n"
    "    } finally {\n"
    "      setLetterPending(false);\n"
    "    }\n"
    "  };\n"
    "\n"
    "  const previewLetter = async () => {\n"
    "    try {\n"
    "      const res = await fetch(`/api/admin/admissions/${id}/letter/download`, { credentials: 'include' });\n"
    "      const result = await res.json();\n"
    "      if (!res.ok || !result.success) throw new Error(result.error || 'Unable to open the letter.');\n"
    "      window.open(result.data.url, '_blank', 'noopener,noreferrer');\n"
    "    } catch (err) {\n"
    "      setActionMessage(err.message);\n"
    "    }\n"
    "  };\n"
    "\n"
    "  if (loading) return <main style={page}><div style={container}>Loading…</div></main>;",
    "letter workflow handlers",
)

# 4) UI: Letter of Admission section, between the actions div and Notes.
c = r1(
    c,
    "              </div>\n"
    "            </div>\n"
    "          )}\n"
    "        </div>\n"
    "\n"
    "        <section className=\"ih-card\" style={{ padding: 20, marginBottom: 18 }}>\n"
    "          <h2 style={{ margin: '0 0 14px', fontSize: 16, color: 'var(--brand)' }}>Notes</h2>",
    "              </div>\n"
    "            </div>\n"
    "          )}\n"
    "        </div>\n"
    "\n"
    "        {a.status === 'APPROVED' && (\n"
    "          <section className=\"ih-card\" style={{ padding: 20, marginBottom: 18 }}>\n"
    "            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 10, marginBottom: 14 }}>\n"
    "              <h2 style={{ margin: 0, fontSize: 16, color: 'var(--brand)' }}>Letter of Admission</h2>\n"
    "              <span\n"
    "                className={`ih-badge ${letter?.status === 'FINALIZED' ? 'ih-b-success' : letter ? 'ih-b-warning' : 'ih-b-neutral'}`}\n"
    "                style={{ fontSize: 11 }}\n"
    "              >\n"
    "                {letter?.status === 'FINALIZED' ? `Finalized · v${letter.version}` : letter ? `Draft · v${letter.version}` : 'Not started'}\n"
    "              </span>\n"
    "            </div>\n"
    "\n"
    "            {letterLoading ? (\n"
    "              <p style={{ fontSize: 13, color: 'var(--ink-soft)', margin: 0 }}>Loading…</p>\n"
    "            ) : (\n"
    "              <>\n"
    "                {letter?.status === 'FINALIZED' && (\n"
    "                  <div style={notFinalNotice}>\n"
    "                    This letter has been finalized and issued to the applicant. To correct it, reopen it first — the currently issued version is preserved.\n"
    "                  </div>\n"
    "                )}\n"
    "\n"
    "                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: 12, margin: '14px 0' }}>\n"
    "                  <label style={letterFieldLabel}>\n"
    "                    Programme\n"
    "                    <input style={letterInput} disabled={letter?.status === 'FINALIZED'} value={letterForm.programmeText} onChange={(e) => setLetterForm((f) => ({ ...f, programmeText: e.target.value }))} />\n"
    "                  </label>\n"
    "                  <label style={letterFieldLabel}>\n"
    "                    Department\n"
    "                    <input style={letterInput} disabled={letter?.status === 'FINALIZED'} value={letterForm.departmentText} onChange={(e) => setLetterForm((f) => ({ ...f, departmentText: e.target.value }))} />\n"
    "                  </label>\n"
    "                  <label style={letterFieldLabel}>\n"
    "                    Qualification\n"
    "                    <input style={letterInput} disabled={letter?.status === 'FINALIZED'} value={letterForm.qualificationText} onChange={(e) => setLetterForm((f) => ({ ...f, qualificationText: e.target.value }))} />\n"
    "                  </label>\n"
    "                  <label style={letterFieldLabel}>\n"
    "                    Intake / Session\n"
    "                    <input style={letterInput} disabled={letter?.status === 'FINALIZED'} value={letterForm.intakeSession} onChange={(e) => setLetterForm((f) => ({ ...f, intakeSession: e.target.value }))} />\n"
    "                  </label>\n"
    "                  <label style={letterFieldLabel}>\n"
    "                    Admission Date\n"
    "                    <input type=\"date\" style={letterInput} disabled={letter?.status === 'FINALIZED'} value={letterForm.admissionDate} onChange={(e) => setLetterForm((f) => ({ ...f, admissionDate: e.target.value }))} />\n"
    "                  </label>\n"
    "                  <label style={letterFieldLabel}>\n"
    "                    Authorized Signatory\n"
    "                    <input style={letterInput} disabled={letter?.status === 'FINALIZED'} value={letterForm.signatoryName} onChange={(e) => setLetterForm((f) => ({ ...f, signatoryName: e.target.value }))} />\n"
    "                  </label>\n"
    "                  <label style={letterFieldLabel}>\n"
    "                    Signatory Title\n"
    "                    <input style={letterInput} disabled={letter?.status === 'FINALIZED'} value={letterForm.signatoryTitle} onChange={(e) => setLetterForm((f) => ({ ...f, signatoryTitle: e.target.value }))} />\n"
    "                  </label>\n"
    "                </div>\n"
    "\n"
    "                <label style={{ ...letterFieldLabel, display: 'block', marginBottom: 14 }}>\n"
    "                  Conditions of Admission (optional)\n"
    "                  <textarea\n"
    "                    style={{ ...letterInput, width: '100%', resize: 'vertical', display: 'block', marginTop: 4 }}\n"
    "                    rows={2}\n"
    "                    disabled={letter?.status === 'FINALIZED'}\n"
    "                    value={letterForm.conditions}\n"
    "                    onChange={(e) => setLetterForm((f) => ({ ...f, conditions: e.target.value }))}\n"
    "                  />\n"
    "                </label>\n"
    "\n"
    "                <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>\n"
    "                  {letter?.status !== 'FINALIZED' && (\n"
    "                    <button className=\"ih-btn ih-btn-secondary\" disabled={letterPending} onClick={() => saveLetterDraft(false)}>\n"
    "                      Save Draft\n"
    "                    </button>\n"
    "                  )}\n"
    "                  {letter?.pdfUrl && (\n"
    "                    <button className=\"ih-btn ih-btn-secondary\" disabled={letterPending} onClick={previewLetter}>\n"
    "                      {letter.status === 'FINALIZED' ? 'Download Letter' : 'Preview Letter'}\n"
    "                    </button>\n"
    "                  )}\n"
    "                  {letter && letter.status !== 'FINALIZED' && (\n"
    "                    <button className=\"ih-btn ih-btn-primary\" disabled={letterPending} onClick={finalizeLetter}>\n"
    "                      Finalize Letter\n"
    "                    </button>\n"
    "                  )}\n"
    "                  {letter?.status === 'FINALIZED' && (\n"
    "                    <button className=\"ih-btn ih-btn-danger\" disabled={letterPending} onClick={() => saveLetterDraft(true)}>\n"
    "                      Reopen for Correction\n"
    "                    </button>\n"
    "                  )}\n"
    "                </div>\n"
    "              </>\n"
    "            )}\n"
    "          </section>\n"
    "        )}\n"
    "\n"
    "        <section className=\"ih-card\" style={{ padding: 20, marginBottom: 18 }}>\n"
    "          <h2 style={{ margin: '0 0 14px', fontSize: 16, color: 'var(--brand)' }}>Notes</h2>",
    "letter of admission UI section",
)

# 5) UI: History section, after the Payment section.
c = r1(
    c,
    "        <Section title=\"Payment\">\n"
    "          <Field label=\"Status\" value={a.payment?.status} />\n"
    "          <Field label=\"Amount\" value={a.payment ? `${a.payment.currencyCode} ${a.payment.amount}` : null} />\n"
    "          <Field label=\"Gateway\" value={a.payment?.gateway} />\n"
    "          <Field label=\"Reference\" value={a.payment?.gatewayReference} />\n"
    "        </Section>\n"
    "      </div>\n"
    "    </main>\n"
    "  );\n"
    "}",
    "        <Section title=\"Payment\">\n"
    "          <Field label=\"Status\" value={a.payment?.status} />\n"
    "          <Field label=\"Amount\" value={a.payment ? `${a.payment.currencyCode} ${a.payment.amount}` : null} />\n"
    "          <Field label=\"Gateway\" value={a.payment?.gateway} />\n"
    "          <Field label=\"Reference\" value={a.payment?.gatewayReference} />\n"
    "        </Section>\n"
    "\n"
    "        <section className=\"ih-card\" style={{ padding: 20, marginBottom: 18 }}>\n"
    "          <h2 style={{ margin: '0 0 14px', fontSize: 16, color: 'var(--brand)' }}>History</h2>\n"
    "          {historyLoading && <p style={{ fontSize: 13, color: 'var(--ink-soft)', margin: 0 }}>Loading…</p>}\n"
    "          {!historyLoading && history.length === 0 && (\n"
    "            <p style={{ fontSize: 13, color: 'var(--ink-soft)', margin: 0 }}>No recorded activity yet.</p>\n"
    "          )}\n"
    "          {!historyLoading && history.length > 0 && (\n"
    "            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>\n"
    "              {history.map((h) => (\n"
    "                <div key={h.id} style={{ padding: '8px 12px', borderRadius: 8, border: '1px solid var(--border, #e2e2e2)', fontSize: 12.5 }}>\n"
    "                  <div style={{ display: 'flex', justifyContent: 'space-between', gap: 10, flexWrap: 'wrap' }}>\n"
    "                    <strong>{h.action.replace(/_/g, ' ')}</strong>\n"
    "                    <span style={{ color: 'var(--ink-soft)' }}>{h.createdAt ? new Date(h.createdAt).toLocaleString() : ''}</span>\n"
    "                  </div>\n"
    "                  {(h.fromStatus || h.toStatus) && (\n"
    "                    <div style={{ color: 'var(--ink-soft)', marginTop: 2 }}>\n"
    "                      {h.fromStatus ? STATUS_LABELS[h.fromStatus] || h.fromStatus : '—'} → {h.toStatus ? STATUS_LABELS[h.toStatus] || h.toStatus : '—'}\n"
    "                    </div>\n"
    "                  )}\n"
    "                  {h.note && <div style={{ marginTop: 2 }}>{h.note}</div>}\n"
    "                  <div style={{ color: 'var(--ink-soft)', marginTop: 2 }}>{h.actorName || 'System'}</div>\n"
    "                </div>\n"
    "              ))}\n"
    "            </div>\n"
    "          )}\n"
    "        </section>\n"
    "      </div>\n"
    "    </main>\n"
    "  );\n"
    "}",
    "history UI section",
)

# 6) New style constants, appended after noteRow.
c = r1(
    c,
    "const noteRow = { padding: '10px 12px', borderRadius: 8, border: '1px solid var(--border, #e2e2e2)' };",
    "const noteRow = { padding: '10px 12px', borderRadius: 8, border: '1px solid var(--border, #e2e2e2)' };\n"
    "const letterFieldLabel = { display: 'flex', flexDirection: 'column', gap: 4, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.4, color: 'var(--ink-soft)', fontWeight: 700 };\n"
    "const letterInput = { padding: '8px 10px', borderRadius: 8, border: '1px solid var(--border, #d8d8d8)', fontFamily: 'inherit', fontSize: 13.5, fontWeight: 400, textTransform: 'none', letterSpacing: 0, color: 'var(--ink)' };",
    "letter style constants",
)

save(path, c)
print("app/admin/admissions/[id]/page.jsx: Letter of Admission + History sections wired in.")
