# -*- coding: utf-8 -*-
import io

def load(path):
    with io.open(path, "r", encoding="utf-8") as f:
        return f.read()

def save(path, content):
    with io.open(path, "w", encoding="utf-8") as f:
        f.write(content)

def r1(content, old, new, label):
    c = content.count(old)
    assert c == 1, "%s: expected 1 match, found %d (context: %r)" % (label, c, old[:120])
    return content.replace(old, new)

path = "app/page.jsx"
c = load(path)

# Academy (green) section.
c = r1(
    c,
    "      <section style={greenSection}>\n"
    "\n"
    "        <div style={sectionInner}>\n"
    "\n"
    "          <span style={goldLabel}>\n"
    "            ACADEMY\n"
    "          </span>\n"
    "\n"
    "          <h2 style={sectionTitleWhite}>\n"
    "            Explore Our Academic Programmes\n"
    "          </h2>\n"
    "\n"
    "          <p style={whiteDescription}>\n"
    "            Explore our academic departments, programmes, courses, and areas\n"
    "            of Islamic study, rooted in the Qur'an and Sunnah and presented\n"
    "            through structured and disciplined learning.\n"
    "          </p>\n"
    "\n"
    "          <div style={miniFeatureGrid}>\n"
    "\n"
    "            <MiniFeature\n"
    "              icon=\"📖\"\n"
    "              text=\"Qur'anic Sciences\"\n"
    "            />\n"
    "\n"
    "            <MiniFeature\n"
    "              icon=\"🗣️\"\n"
    "              text=\"Arabic Language\"\n"
    "            />\n"
    "\n"
    "            <MiniFeature\n"
    "              icon=\"📚\"\n"
    "              text=\"Hadith Studies\"\n"
    "            />\n"
    "\n"
    "            <MiniFeature\n"
    "              icon=\"⚖️\"\n"
    "              text=\"Fiqh & Usul\"\n"
    "            />\n"
    "\n"
    "            <MiniFeature\n"
    "              icon=\"☪️\"\n"
    "              text=\"Aqidah\"\n"
    "            />\n"
    "\n"
    "            <MiniFeature\n"
    "              icon=\"🎙️\"\n"
    "              text=\"Tajwid & Recitation\"\n"
    "            />\n"
    "\n"
    "            <MiniFeature\n"
    "              icon=\"☪️\"\n"
    "              text=\"Tauheed (Monotheism)\"\n"
    "            />\n"
    "\n"
    "            <MiniFeature\n"
    "              icon=\"🌱\"\n"
    "              text=\"Tarbiyah (Education)\"\n"
    "            />\n"
    "\n"
    "          </div>\n"
    "\n"
    "          <Link\n"
    "            href=\"/programs\"\n"
    "            style={goldButton}\n"
    "          >\n"
    "            Explore Academic Departments →\n"
    "          </Link>\n"
    "\n"
    "        </div>\n"
    "\n"
    "      </section>",
    "      <section style={greenSection} dir={dir}>\n"
    "\n"
    "        <div style={sectionInner}>\n"
    "\n"
    "          <span style={goldLabel}>\n"
    "            {t('ACADEMY')}\n"
    "          </span>\n"
    "\n"
    "          <h2 style={sectionTitleWhite}>\n"
    "            {t('Explore Our Academic Programmes')}\n"
    "          </h2>\n"
    "\n"
    "          <p style={whiteDescription}>\n"
    "            {t(\"Explore our academic departments, programmes, courses, and areas of Islamic study, rooted in the Qur'an and Sunnah and presented through structured and disciplined learning.\")}\n"
    "          </p>\n"
    "\n"
    "          <div style={miniFeatureGrid}>\n"
    "\n"
    "            <MiniFeature\n"
    "              icon=\"📖\"\n"
    "              text={t(\"Qur'anic Sciences\")}\n"
    "            />\n"
    "\n"
    "            <MiniFeature\n"
    "              icon=\"🗣️\"\n"
    "              text={t('Arabic Language')}\n"
    "            />\n"
    "\n"
    "            <MiniFeature\n"
    "              icon=\"📚\"\n"
    "              text={t('Hadith Studies')}\n"
    "            />\n"
    "\n"
    "            <MiniFeature\n"
    "              icon=\"⚖️\"\n"
    "              text={t('Fiqh & Usul')}\n"
    "            />\n"
    "\n"
    "            <MiniFeature\n"
    "              icon=\"☪️\"\n"
    "              text={t('Aqidah')}\n"
    "            />\n"
    "\n"
    "            <MiniFeature\n"
    "              icon=\"🎙️\"\n"
    "              text={t('Tajwid & Recitation')}\n"
    "            />\n"
    "\n"
    "            <MiniFeature\n"
    "              icon=\"☪️\"\n"
    "              text={t('Tauheed (Monotheism)')}\n"
    "            />\n"
    "\n"
    "            <MiniFeature\n"
    "              icon=\"🌱\"\n"
    "              text={t('Tarbiyah (Education)')}\n"
    "            />\n"
    "\n"
    "          </div>\n"
    "\n"
    "          <Link\n"
    "            href=\"/programs\"\n"
    "            style={goldButton}\n"
    "          >\n"
    "            {t('Explore Academic Departments →')}\n"
    "          </Link>\n"
    "\n"
    "        </div>\n"
    "\n"
    "      </section>",
    "page: Academy green section translation",
)

# Bookstore section.
c = r1(
    c,
    "      <section style={sectionStyle}>\n"
    "\n"
    "        <div style={splitGrid}>\n"
    "\n"
    "          <div>\n"
    "\n"
    "            <span style={goldLabel}>\n"
    "              ULUL AZM BOOKSTORE\n"
    "            </span>\n"
    "\n"
    "            <h2\n"
    "              style={{\n"
    "                ...sectionTitle,\n"
    "                textAlign: 'left',\n"
    "                whiteSpace: 'normal',\n"
    "              }}\n"
    "            >\n"
    "              Islamic Bookstore\n"
    "            </h2>\n"
    "\n"
    "            <p\n"
    "              style={{\n"
    "                ...sectionDescription,\n"
    "                textAlign: 'left',\n"
    "                margin: '0',\n"
    "              }}\n"
    "            >\n"
    "              Explore selected Islamic books, classical texts, student\n"
    "              resources, workbooks and educational publications.\n"
    "            </p>\n"
    "\n"
    "            <div style={buttonRow}>\n"
    "\n"
    "              <Link\n"
    "                href=\"/bookstore\"\n"
    "                style={mainButton}\n"
    "              >\n"
    "                Visit Islamic Bookstore →\n"
    "              </Link>\n"
    "\n"
    "              <Link\n"
    "                href=\"/author-portal/admission\"\n"
    "                style={outlineButton}\n"
    "              >\n"
    "                Become an Author & Sell Your Books\n"
    "              </Link>\n"
    "\n"
    "            </div>\n"
    "\n"
    "          </div>\n"
    "\n"
    "          <div style={bookstoreFeature}>\n"
    "\n"
    "            <div style={{ fontSize: '50px' }}>\n"
    "              📚\n"
    "            </div>\n"
    "\n"
    "            <h3 style={featureDarkTitle}>\n"
    "              Beneficial Knowledge\n"
    "            </h3>\n"
    "\n"
    "            <p style={featureDarkText}>\n"
    "              Quality books are companions for the serious student. Explore\n"
    "              our dedicated bookstore for academic and Islamic publications.\n"
    "            </p>\n"
    "\n"
    "          </div>\n"
    "\n"
    "        </div>\n"
    "\n"
    "      </section>",
    "      <section style={sectionStyle} dir={dir}>\n"
    "\n"
    "        <div style={splitGrid}>\n"
    "\n"
    "          <div>\n"
    "\n"
    "            <span style={goldLabel}>\n"
    "              {t('ULUL AZM BOOKSTORE')}\n"
    "            </span>\n"
    "\n"
    "            <h2\n"
    "              style={{\n"
    "                ...sectionTitle,\n"
    "                textAlign: dir === 'rtl' ? 'right' : 'left',\n"
    "                whiteSpace: 'normal',\n"
    "              }}\n"
    "            >\n"
    "              {t('Islamic Bookstore')}\n"
    "            </h2>\n"
    "\n"
    "            <p\n"
    "              style={{\n"
    "                ...sectionDescription,\n"
    "                textAlign: dir === 'rtl' ? 'right' : 'left',\n"
    "                margin: '0',\n"
    "              }}\n"
    "            >\n"
    "              {t('Explore selected Islamic books, classical texts, student resources, workbooks and educational publications.')}\n"
    "            </p>\n"
    "\n"
    "            <div style={buttonRow}>\n"
    "\n"
    "              <Link\n"
    "                href=\"/bookstore\"\n"
    "                style={mainButton}\n"
    "              >\n"
    "                {t('Visit Islamic Bookstore →')}\n"
    "              </Link>\n"
    "\n"
    "              <Link\n"
    "                href=\"/author-portal/admission\"\n"
    "                style={outlineButton}\n"
    "              >\n"
    "                {t('Become an Author & Sell Your Books')}\n"
    "              </Link>\n"
    "\n"
    "            </div>\n"
    "\n"
    "          </div>\n"
    "\n"
    "          <div style={bookstoreFeature}>\n"
    "\n"
    "            <div style={{ fontSize: '50px' }}>\n"
    "              📚\n"
    "            </div>\n"
    "\n"
    "            <h3 style={featureDarkTitle}>\n"
    "              {t('Beneficial Knowledge')}\n"
    "            </h3>\n"
    "\n"
    "            <p style={featureDarkText}>\n"
    "              {t('Quality books are companions for the serious student. Explore our dedicated bookstore for academic and Islamic publications.')}\n"
    "            </p>\n"
    "\n"
    "          </div>\n"
    "\n"
    "        </div>\n"
    "\n"
    "      </section>",
    "page: Bookstore section translation",
)

save(path, c)
print("app/page.jsx: pass 2b (Academy green section + Bookstore section) done.")
