# -*- coding: utf-8 -*-
import io

def load(path):
    with io.open(path, "r", encoding="utf-8") as f:
        return f.read()

def save(path, content):
    with io.open(path, "w", encoding="utf-8") as f:
        f.write(content)

def r1(content, old, new, label):
    c = content.count(old)
    assert c == 1, "%s: expected 1 match, found %d (context: %r)" % (label, c, old[:160])
    return content.replace(old, new)

# =======================================================================
# app/page.jsx -- AnnouncementsStrip already pulls real Announcement
# records from /api/announcements (and already renders nothing when
# there are none, which is correct -- it stays that way). It just showed
# them as a static grid; this turns it into an auto-advancing slider
# with dot navigation, paused for anyone with prefers-reduced-motion,
# and only auto-plays when there's more than one notice to show.
# =======================================================================
path = "app/page.jsx"
c = load(path)

c = r1(
    c,
    "function AnnouncementsStrip() {\n"
    "  const { t, dir } = useLanguage();\n"
    "  const [announcements, setAnnouncements] = useState([]);\n"
    "  const [loaded, setLoaded] = useState(false);\n"
    "\n"
    "  useEffect(() => {\n"
    "    let cancelled = false;\n"
    "\n"
    "    fetch('/api/announcements')\n"
    "      .then((res) => res.json())\n"
    "      .then((result) => {\n"
    "        if (cancelled) return;\n"
    "        if (result && result.success && Array.isArray(result.data)) {\n"
    "          setAnnouncements(result.data);\n"
    "        }\n"
    "      })\n"
    "      .catch(() => {\n"
    "        /* silently ignore — the homepage should never break because\n"
    "           the announcements feed is unavailable */\n"
    "      })\n"
    "      .finally(() => {\n"
    "        if (!cancelled) setLoaded(true);\n"
    "      });\n"
    "\n"
    "    return () => {\n"
    "      cancelled = true;\n"
    "    };\n"
    "  }, []);\n"
    "\n"
    "  if (!loaded || announcements.length === 0) {\n"
    "    return null;\n"
    "  }\n"
    "\n"
    "  return (\n"
    "    <section style={announcementsSectionStyle} dir={dir}>\n"
    "      <div style={headingContainer}>\n"
    "        <span style={goldLabel}>{t('NOTICES & ANNOUNCEMENTS')}</span>\n"
    "\n"
    "        <h2 style={sectionTitle}>\n"
    "          {t(\"What's happening at Ulul Azm\")}\n"
    "        </h2>\n"
    "      </div>\n"
    "\n"
    "      <div style={announcementsGrid}>\n"
    "        {announcements.map((item) => (\n"
    "          <div key={item.id} style={announcementCard}>\n"
    "            <div style={announcementDate}>\n"
    "              {new Date(item.publishedAt).toLocaleDateString([], {\n"
    "                year: 'numeric',\n"
    "                month: 'short',\n"
    "                day: 'numeric',\n"
    "              })}\n"
    "            </div>\n"
    "\n"
    "            <h3 style={announcementTitle}>{item.titleEn}</h3>\n"
    "\n"
    "            <p style={announcementBody}>{item.bodyEn}</p>\n"
    "          </div>\n"
    "        ))}\n"
    "      </div>\n"
    "    </section>\n"
    "  );\n"
    "}",
    "function AnnouncementsStrip() {\n"
    "  const { t, dir } = useLanguage();\n"
    "  const [announcements, setAnnouncements] = useState([]);\n"
    "  const [loaded, setLoaded] = useState(false);\n"
    "  const [activeIndex, setActiveIndex] = useState(0);\n"
    "\n"
    "  useEffect(() => {\n"
    "    let cancelled = false;\n"
    "\n"
    "    fetch('/api/announcements')\n"
    "      .then((res) => res.json())\n"
    "      .then((result) => {\n"
    "        if (cancelled) return;\n"
    "        if (result && result.success && Array.isArray(result.data)) {\n"
    "          setAnnouncements(result.data);\n"
    "        }\n"
    "      })\n"
    "      .catch(() => {\n"
    "        /* silently ignore — the homepage should never break because\n"
    "           the announcements feed is unavailable */\n"
    "      })\n"
    "      .finally(() => {\n"
    "        if (!cancelled) setLoaded(true);\n"
    "      });\n"
    "\n"
    "    return () => {\n"
    "      cancelled = true;\n"
    "    };\n"
    "  }, []);\n"
    "\n"
    "  // Auto-advance the slider -- only when there's more than one notice,\n"
    "  // and never for anyone whose system asks for reduced motion.\n"
    "  useEffect(() => {\n"
    "    if (announcements.length < 2) return undefined;\n"
    "    if (\n"
    "      typeof window !== 'undefined' &&\n"
    "      window.matchMedia &&\n"
    "      window.matchMedia('(prefers-reduced-motion: reduce)').matches\n"
    "    ) {\n"
    "      return undefined;\n"
    "    }\n"
    "\n"
    "    const timer = setInterval(() => {\n"
    "      setActiveIndex((index) => (index + 1) % announcements.length);\n"
    "    }, 6000);\n"
    "\n"
    "    return () => clearInterval(timer);\n"
    "  }, [announcements.length]);\n"
    "\n"
    "  if (!loaded || announcements.length === 0) {\n"
    "    return null;\n"
    "  }\n"
    "\n"
    "  return (\n"
    "    <section style={announcementsSectionStyle} dir={dir}>\n"
    "      <div style={headingContainer}>\n"
    "        <span style={goldLabel}>{t('NOTICES & ANNOUNCEMENTS')}</span>\n"
    "\n"
    "        <h2 style={sectionTitle}>\n"
    "          {t(\"What's happening at Ulul Azm\")}\n"
    "        </h2>\n"
    "      </div>\n"
    "\n"
    "      <div style={announcementsSliderViewport}>\n"
    "        <div\n"
    "          style={{\n"
    "            ...announcementsSliderTrack,\n"
    "            transform: `translateX(-${activeIndex * 100}%)`,\n"
    "          }}\n"
    "        >\n"
    "          {announcements.map((item) => (\n"
    "            <div key={item.id} style={announcementsSlide}>\n"
    "              <div style={announcementCard}>\n"
    "                <div style={announcementDate}>\n"
    "                  {new Date(item.publishedAt).toLocaleDateString([], {\n"
    "                    year: 'numeric',\n"
    "                    month: 'short',\n"
    "                    day: 'numeric',\n"
    "                  })}\n"
    "                </div>\n"
    "\n"
    "                <h3 style={announcementTitle}>{item.titleEn}</h3>\n"
    "\n"
    "                <p style={announcementBody}>{item.bodyEn}</p>\n"
    "              </div>\n"
    "            </div>\n"
    "          ))}\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      {announcements.length > 1 && (\n"
    "        <div style={announcementsDots} role=\"tablist\" aria-label=\"Announcements\">\n"
    "          {announcements.map((item, index) => (\n"
    "            <button\n"
    "              key={item.id}\n"
    "              type=\"button\"\n"
    "              role=\"tab\"\n"
    "              onClick={() => setActiveIndex(index)}\n"
    "              aria-label={`Show notice ${index + 1} of ${announcements.length}`}\n"
    "              aria-selected={index === activeIndex}\n"
    "              style={index === activeIndex ? announcementsDotActive : announcementsDot}\n"
    "            />\n"
    "          ))}\n"
    "        </div>\n"
    "      )}\n"
    "    </section>\n"
    "  );\n"
    "}",
    "app/page.jsx: AnnouncementsStrip becomes an auto-advancing slider",
)

c = r1(
    c,
    "const announcementsGrid = {\n"
    "  display: 'grid',\n"
    "  gridTemplateColumns: 'repeat(auto-fit,minmax(260px,1fr))',\n"
    "  gap: '18px',\n"
    "  marginTop: '10px',\n"
    "};",
    "const announcementsGrid = {\n"
    "  display: 'grid',\n"
    "  gridTemplateColumns: 'repeat(auto-fit,minmax(260px,1fr))',\n"
    "  gap: '18px',\n"
    "  marginTop: '10px',\n"
    "};\n"
    "\n"
    "const announcementsSliderViewport = {\n"
    "  overflow: 'hidden',\n"
    "  marginTop: '10px',\n"
    "};\n"
    "\n"
    "const announcementsSliderTrack = {\n"
    "  display: 'flex',\n"
    "  transition: 'transform 0.6s ease',\n"
    "};\n"
    "\n"
    "const announcementsSlide = {\n"
    "  flex: '0 0 100%',\n"
    "  minWidth: '100%',\n"
    "  boxSizing: 'border-box',\n"
    "  padding: '2px',\n"
    "};\n"
    "\n"
    "const announcementsDots = {\n"
    "  display: 'flex',\n"
    "  justifyContent: 'center',\n"
    "  gap: '8px',\n"
    "  marginTop: '18px',\n"
    "};\n"
    "\n"
    "const announcementsDot = {\n"
    "  width: '8px',\n"
    "  height: '8px',\n"
    "  borderRadius: '50%',\n"
    "  border: 'none',\n"
    "  background: 'var(--border)',\n"
    "  cursor: 'pointer',\n"
    "  padding: 0,\n"
    "  transition: 'width 0.2s ease, border-radius 0.2s ease, background 0.2s ease',\n"
    "};\n"
    "\n"
    "const announcementsDotActive = {\n"
    "  ...announcementsDot,\n"
    "  width: '22px',\n"
    "  borderRadius: '5px',\n"
    "  background: 'var(--gold)',\n"
    "};",
    "app/page.jsx: add slider/dots styles",
)

save(path, c)
print("app/page.jsx: the announcements section now slides through notices automatically, with dot navigation, once any are published.")
